import type { TattooMotifProfile } from "./tattoo-motif-profiles.ts";

/**
 * Curated extras for the piercing articles, in the same shape as the tattoo profiles. Articles
 * without a profile fall back to what their own text names (see tattoo-motifs.ts).
 */
export const PIERCING_MOTIF_PROFILES: Record<string, TattooMotifProfile> = {
  "ashley-piercing": {
    motif: "Ashley",
    glanceTitle: "Ashley Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Lippenrot", "Mitte der Unterlippe", "Diagonal gestochen"] },
      { label: "Schmuck", items: ["Curved Barbell", "Labret Stecker", "Sichtbare Kugel"] },
      { label: "Wirkt", items: ["Betont die Lippen", "Voller wirkend", "Blickfang Mund"] },
    ],
    flirtHook: {
      title: "Alle Augen auf den Mund",
      text: "Ein Ashley Piercing lenkt den Blick genau dorthin, wo das Gespräch passiert. Frag, ob es schon oft mit einem Eskimo Piercing verwechselt wurde – beide gehen durchs Lippenrot, aber nur beim Eskimo sieht man zwei Kugeln.",
    },
    hookLinkLabel: "Singles mit Lippenpiercing entdecken →",
    sceneLine: "Madonna und Amy Winehouse haben das Ashley bekannt gemacht, getragen wird es heute aus ganz eigenen Gründen. Bei Dich mit Stich erzählen Singles, welche das sind.",
    pullQuote: "Die Kugel zieht die Aufmerksamkeit auf den Mund, bringt die Lippen zur Geltung und lässt sie voller wirken.",
    related: ["eskimo-piercing", "labret-piercing", "lippenpiercing"],
  },
  "augenbrauen-piercing": {
    motif: "Augenbraue",
    glanceTitle: "Augenbrauen Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Äußeres Brauendrittel", "Vertikal", "Horizontal"] },
      { label: "Schmuck", items: ["Barbell", "Curved Barbell", "Ball Closure Ring"] },
      { label: "Bekannt durch", items: ["Punk-Bewegung", "1990er Jahre", "Nu-Metal"] },
    ],
    flirtHook: {
      title: "Ehrlich bis in die Braue",
      text: "Die Augenbrauen gelten als ehrlichster Teil des Gesichts – ein Piercing dort setzt genau diesen Akzent. Frag, ob es aus den 90ern stammt oder ganz frisch ist. Die Antwort erzählt oft eine kleine Musikgeschichte.",
    },
    hookLinkLabel: "Singles mit Gesichtspiercing in deiner Nähe finden →",
    sceneLine: "Ein Brauenpiercing trägt man offen, jeden Tag, vor allen. Bei Dich mit Stich zeigen Singles genau das im Profil – und werden dafür nicht schief angeschaut.",
    pullQuote: "Körpersprache-Forscher fanden heraus, dass die Augenbrauen der ehrlichste Teil unseres Gesichtes sind.",
    related: ["bridge-piercing", "surface-piercing", "septum-piercing"],
  },
  "austin-bar-piercing": {
    motif: "Austin Bar",
    glanceTitle: "Austin Bar Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nasenspitze", "Horizontal", "Beide Nasenseiten"] },
      { label: "Hintergrund", items: ["Mittlerer Osten", "Indien", "Tapferkeit & Mut"] },
      { label: "Vorher klären", items: ["Profi-Studio", "Referenzbilder ansehen", "Nicht als Erstpiercing"] },
    ],
    flirtHook: {
      title: "Selten, aber gesehen",
      text: "Ein Austin Bar trägt kaum jemand – wer es hat, wollte bewusst auffallen. Frag, ob es das erste Piercing war oder eher der Höhepunkt einer Sammlung. Seltene Entscheidungen erzählen die besten Geschichten.",
    },
    hookLinkLabel: "Singles mit besonderem Piercing entdecken →",
    sceneLine: "Wer ein Piercing trägt, das kaum jemand kennt, erklärt es ständig. Bei Dich mit Stich treffen sich Singles, die solche Besonderheiten zu schätzen wissen.",
    pullQuote: "Es wird vor allem von Leuten genutzt, die ein besonderes Piercing wollen, mit dem sie auf jeden Fall auffallen.",
    related: ["nasallang-piercing", "bridge-piercing", "nostril-piercing"],
  },
  "bauchnabelpiercing": {
    motif: "Bauchnabel",
    glanceTitle: "Bauchnabelpiercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Oberer Nabelrand", "Unter dem Nabel", "Links oder rechts"] },
      { label: "Schmuck", items: ["Curved Barbell", "Banane", "Spirale", "Kugel"] },
      { label: "Wirkt", items: ["Verdeckbar", "90er-Klassiker", "Verspielt"] },
    ],
    flirtHook: {
      title: "Mal sichtbar, mal nicht",
      text: "Ein Bauchnabelpiercing verschwindet unter jedem Shirt – und ist trotzdem ein Stück Persönlichkeit. Ob 90er-Nostalgie oder ganz neu gestochen: Die Geschichte dazu erzählt man gern, wenn jemand ehrlich fragt.",
    },
    hookLinkLabel: "Gepiercte Singles aus deiner Stadt kennenlernen →",
    sceneLine: "Manche Piercings zeigt man erst, wenn man jemanden kennt. Bei Dich mit Stich lernst du Singles kennen, die für Körperschmuck genauso viel übrig haben wie du.",
    pullQuote: "Ein Bauchnabelpiercing wird meist von Frauen getragen und ist an verschiedenen Stellen rund um den Bauchnabel möglich.",
    related: ["surface-piercing", "brustwarzenpiercing", "deep-chest-piercing"],
  },
  "bridge-piercing": {
    motif: "Bridge",
    glanceTitle: "Bridge Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nasenrücken", "Zwischen den Augen", "Gesichtsmitte"] },
      { label: "Bekannt als", items: ["Bridge Piercing", "Erl Piercing", "Niebuhr Piercing"] },
      { label: "Vorher klären", items: ["Erfahrener Piercer", "Eigene Anatomie", "Genaue Platzierung", "Pflege ohne Makeup"] },
    ],
    flirtHook: {
      title: "Blickfang zwischen den Augen",
      text: "Ein Bridge Piercing lenkt den Blick direkt auf die Augen – und genau dort beginnt jedes gute Gespräch. Frag, wie lange die Suche nach dem richtigen Piercer gedauert hat. Wer sich dafür Zeit nimmt, hat meist auch sonst einen klaren Plan.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Nähe kennenlernen →",
    sceneLine: "Ein Bridge Piercing sieht man sofort, auch im ersten Profilbild. Bei Dich mit Stich ist das kein Risiko, sondern ein guter Anfang.",
    pullQuote: "Das Bridge Piercing hebt die Ebenmäßigkeit und die Symmetrie des Gesichts hervor, wenn es an der richtigen Stelle gestochen wird.",
    related: ["augenbrauen-piercing", "septum-piercing", "austin-bar-piercing"],
  },
  "brustwarzenpiercing": {
    motif: "Brustwarze",
    glanceTitle: "Brustwarzenpiercing: das Wichtigste",
    facts: [
      { label: "Varianten", items: ["Horizontal", "Vertikal", "Durch den Warzenhof", "Ein- oder beidseitig"] },
      { label: "Schmuck", items: ["Barbell", "Ball Closure Ring", "Nippelshield"] },
      { label: "Vorher klären", items: ["Seriöses Studio", "Erstschmuck", "Beruf & Kleidung"] },
    ],
    flirtHook: {
      title: "Privat, aber kein Tabu",
      text: "Ein Brustwarzenpiercing ist eine sehr persönliche Entscheidung – bei Frauen wie bei Männern. Wer offen damit umgeht, sucht meist jemanden, der Körperschmuck selbstverständlich findet. Ob und wann man darüber spricht, bestimmst du.",
    },
    hookLinkLabel: "Offene Singles in deiner Nähe entdecken →",
    sceneLine: "Was du von dir zeigst, entscheidest du selbst. Bei Dich mit Stich triffst du Singles, für die Piercings kein Grund für Getuschel sind.",
    pullQuote: "Grundsätzlich kann es jeder tragen und es ist bei Männern und Frauen gleichermaßen angesagt.",
    related: ["deep-chest-piercing", "bauchnabelpiercing", "intimpiercing"],
  },
  "cheek-piercing": {
    motif: "Cheek",
    glanceTitle: "Cheek Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Wange", "Grübchenstelle", "Oft beidseitig"] },
      { label: "Hintergrund", items: ["Tupinamba in Brasilien", "Thaipusam-Fest", "Modeschmuck ab 1990"] },
      { label: "Schmuck", items: ["Labret-Stecker", "Stab", "Dermal Anchor"] },
    ],
    flirtHook: {
      title: "Grübchen mit Absicht",
      text: "Ein Cheek Piercing sitzt genau da, wo sonst beim Lächeln Grübchen entstehen. Da liegt die Frage nahe, ob das Lächeln schon vorher so gewinnend war. Ein Kompliment, das zum Piercing passt, bleibt hängen.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Stadt entdecken →",
    sceneLine: "Ein Wangenpiercing ist selten und fällt bei jedem Lächeln auf. Bei Dich mit Stich lernst du Menschen kennen, die genau das an dir mögen.",
    pullQuote: "Es trägt auch die Bezeichnung „Dimple Piercing“, weil es im Wangenbereich an einer Grübchenstelle gestochen wird.",
    related: ["labret-piercing", "kinnpiercing", "surface-piercing"],
  },
  "christina-piercing": {
    motif: "Christina",
    glanceTitle: "Christina-Piercing: das Wichtigste",
    facts: [
      { label: "Sitzt an", items: ["Unterster Venushügel", "Über den Schamlippen"] },
      { label: "Auch genannt", items: ["Venus-Piercing", "Oberflächenpiercing"] },
      { label: "Vorher klären", items: ["Passende Anatomie", "Vertrauensvolles Studio", "Alltag & Sport"] },
    ],
    flirtHook: {
      title: "Schlicht und selbstbestimmt",
      text: "Das Christina-Piercing überzeugt viele Trägerinnen durch sein schlichtes Design – eine Entscheidung ganz für sich selbst. Wer so selbstbestimmt mit dem eigenen Körper umgeht, verdient ein Gegenüber, das Grenzen respektiert.",
    },
    hookLinkLabel: "Respektvolle Singles in deiner Nähe finden →",
    sceneLine: "Du bestimmst, was du von dir erzählst. Bei Dich mit Stich lernst du Singles kennen, für die Körperschmuck selbstverständlich ist.",
    pullQuote: "Wichtig ist vor allem ein vertrauensvoller Eindruck und eine saubere, professionelle Arbeitsweise.",
    related: ["intimpiercing", "surface-piercing", "brustwarzenpiercing"],
  },
  "conch-piercing": {
    motif: "Conch",
    glanceTitle: "Conch-Piercing in 20 Sekunden",
    facts: [
      { label: "Varianten", items: ["Inner Conch", "Outer Conch", "Größerer Durchmesser"] },
      { label: "Schmuck", items: ["Stecker", "Ring", "Barbell", "Ball Closure Ring"] },
      { label: "Technik", items: ["Piercing-Nadel", "Receiving Tube", "Dermal Punch"] },
    ],
    flirtHook: {
      title: "Mitten in der Muschel",
      text: "Inner oder Outer Conch? Die Frage klingt nach Fachsimpelei, ist aber ein charmanter Einstieg – und zeigt, dass du genauer hinschaust als die meisten.",
    },
    hookLinkLabel: "Ohrschmuck-Fans in deiner Stadt entdecken →",
    sceneLine: "Ein Conch ist ein Statement mitten im Ohr. Bei Dich mit Stich treffen solche Statements auf Singles, die sie zu lesen wissen.",
    pullQuote: "Die unterschiedlichen Möglichkeiten des Designs machen das Piercing zu einem beliebten Trend – außerdem ist es ein wahrer Hingucker.",
    related: ["ohrmuschel-piercing", "helix-piercing", "daith-piercing"],
  },
  "daith-piercing": {
    motif: "Daith",
    glanceTitle: "Daith-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Crus helicis", "Über dem Gehörgang", "Knorpelfalte"] },
      { label: "Name kommt von", items: ["Daath", "Hebräisch für Wissen", "Erik Dakota"] },
      { label: "Schmuck später", items: ["Ball Closure Ring", "Barbell"] },
    ],
    flirtHook: {
      title: "Ein Name voller Wissen",
      text: "Daith leitet sich vom hebräischen Wort für Wissen ab. Frag ruhig, ob die Optik den Ausschlag gegeben hat oder die Geschichten, die man sich über dieses Piercing erzählt – das ist allemal spannender als Smalltalk übers Wetter.",
    },
    hookLinkLabel: "Singles mit Daith & Co. in deiner Stadt finden →",
    sceneLine: "Ein Daith zeigt Stil und Geduld. Bei Dich mit Stich triffst du Singles, die beides zu schätzen wissen.",
    pullQuote: "Sie lassen sich das Ohr nicht zum Zweck der Heilung piercen – sondern als Ausdruck individueller Ästhetik.",
    related: ["rook-piercing", "tragus-piercing", "conch-piercing"],
  },
  "deep-chest-piercing": {
    motif: "Deep Chest",
    glanceTitle: "Deep Chest Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Brust", "Horizontal", "Vertikal", "Beliebiger Winkel"] },
      { label: "Methoden", items: ["Barbell-Methode", "Dermaler Anker"] },
      { label: "Braucht", items: ["Erfahrene Profis", "Geduld", "Sorgfältige Pflege"] },
    ],
    flirtHook: {
      title: "Nichts für nebenbei",
      text: "Ein Deep Chest Piercing wählt niemand aus einer Laune heraus. Wer so etwas trägt, hat meist eine klare Haltung zu Body Mods – und freut sich über ein Gegenüber, das nachfragt statt die Augen zu verdrehen.",
    },
    hookLinkLabel: "Body-Mod-Fans in deiner Nähe entdecken →",
    sceneLine: "Auffällig, speziell und bewusst gewählt: Bei Dich mit Stich triffst du Singles, die genau das an Körperschmuck schätzen.",
    pullQuote: "Es wird meist von Menschen gewählt, die sich bewusst für einen auffälligeren und besonderen Look entscheiden.",
    related: ["surface-piercing", "brustwarzenpiercing", "bauchnabelpiercing"],
  },
  "eskimo-piercing": {
    motif: "Eskimo",
    glanceTitle: "Eskimo Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Mitte der Unterlippe", "Hinter dem Lippenrot", "Senkrecht gestochen"] },
      { label: "Schmuck", items: ["Gebogene Stäbe", "Ringe", "Glitzerkugel"] },
      { label: "Wirkt", items: ["Klar und schlicht", "Edel", "Wie ein Stecker"] },
    ],
    flirtHook: {
      title: "Mittig ins Gespräch",
      text: "Ein Eskimo Piercing sitzt genau in der Mitte der Unterlippe und wirkt oft wie ein einzelner Stecker. Frag nach der Lieblingskombination mit Lippenstift oder Schmuckaufsatz. Wer sich über Details Gedanken macht, hat meist auch im Gespräch einiges zu erzählen.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Nähe entdecken →",
    sceneLine: "Das Eskimo ist ein Trend-Piercing, das trotzdem zu dir passen soll. Bei Dich mit Stich lernst du Singles kennen, die ihren eigenen Look genauso ernst nehmen.",
    pullQuote: "Tolle Kombinationen mit unterschiedlichen Lippenstiften sind möglich und werden somit zum absoluten Hingucker.",
    related: ["ashley-piercing", "labret-piercing", "medusa-piercing"],
  },
  "flesh-tunnel": {
    motif: "Flesh Tunnel",
    glanceTitle: "Flesh Tunnel in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Ohrläppchen", "Gedehntes Ohrloch"] },
      { label: "Varianten", items: ["Double Flared Tunnel", "Tubes mit O-Ringen", "Mit Schraubgewinde"] },
      { label: "Materialien", items: ["Titan", "Holz", "Horn", "Glas", "Silikon"] },
    ],
    flirtHook: {
      title: "Millimeter für Millimeter",
      text: "Ein Flesh Tunnel entsteht nicht über Nacht – dahinter steckt Geduld. Frag, bei welcher Größe jemand angefangen hat und wo die Reise hingehen soll. Von Ötzi bis Double Flared gibt es genug Gesprächsstoff.",
    },
    hookLinkLabel: "Singles mit Tunnels in deiner Nähe finden →",
    sceneLine: "Wer dehnt, denkt langfristig. Bei Dich mit Stich treffen sich Singles, die ihren Stil nicht nach dem nächsten Trend ausrichten.",
    pullQuote: "Für Einsteiger ist wichtig: Ein Flesh Tunnel ist nicht einfach nur Schmuck, sondern setzt meist ein bereits verändertes Ohrloch voraus.",
    related: ["lobe-piercing", "ohrmuschel-piercing", "helix-piercing"],
  },
  "frenulum-piercing": {
    motif: "Frenulum",
    glanceTitle: "Frenulum-Piercing: das Wichtigste",
    facts: [
      { label: "Sitzt an", items: ["Vorhautbändchen", "Unter der Eichel"] },
      { label: "Schmuck", items: ["Curved Barbell", "Surface Bar", "Ring", "Frenum Ladder"] },
      { label: "Gilt als", items: ["Einstiegspiercing", "Beliebtes Intimpiercing"] },
    ],
    flirtHook: {
      title: "Offen, ohne Show",
      text: "Ein Frenulum-Piercing ist für viele Männer das erste Intimpiercing – eine private Entscheidung, die niemandem erklärt werden muss. Wer trotzdem offen über Körperschmuck spricht, zeigt vor allem eins: Vertrauen.",
    },
    hookLinkLabel: "Aufgeschlossene Singles in deiner Nähe entdecken →",
    sceneLine: "Nicht jedes Piercing gehört ins Profilbild – aber es gehört zu dir. Bei Dich mit Stich triffst du Singles, die das verstehen.",
    pullQuote: "Heutzutage ist das Frenulum-Piercing eines der beliebtesten Intimpiercings bei Männern.",
    related: ["prinz-albert-piercing", "penispiercing", "intimpiercing"],
  },
  "helix-piercing": {
    motif: "Helix",
    glanceTitle: "Helix-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Helix", "Knorpelrand der Ohrmuschel", "Frei wählbare Stelle"] },
      { label: "Wirkt", items: ["Hingucker", "Nicht zu auffällig", "Hinter Haaren versteckbar"] },
      { label: "Vorher klären", items: ["Seriöses Studio", "Schmuck & Position", "Schlafen", "Kopfbedeckungen"] },
    ],
    flirtHook: {
      title: "Der sanfte Einstieg",
      text: "Für viele ist das Helix der erste Schritt in die Piercingwelt – sichtbar, aber nicht zu laut. Frag, ob es dabei geblieben ist oder ob schon das nächste geplant ist.",
    },
    hookLinkLabel: "Knorpel-Fans in deiner Nähe entdecken →",
    sceneLine: "Ein Helix blitzt oft nur kurz hinter den Haaren hervor. Bei Dich mit Stich darfst du zeigen, was sonst nur zwischendurch auffällt.",
    pullQuote: "Er ist ein echter Hingucker und ein guter Einstieg, wenn man sich für Piercings interessiert, sich aber noch nicht traut, sich eines im Gesicht stechen zu lassen.",
    related: ["ohrmuschel-piercing", "industrial-piercing", "rook-piercing"],
  },
  "industrial-piercing": {
    motif: "Industrial",
    glanceTitle: "Industrial Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Obere Ohrmuschel", "Helix", "Zwei Stichkanäle"] },
      { label: "Auch genannt", items: ["Crossbow", "Scaffold", "Transversal"] },
      { label: "Schmuck", items: ["Gerades Barbell", "Mit Kristallen", "Mit Ornamenten", "Mit Symbolen"] },
    ],
    flirtHook: {
      title: "Die Stange als Statement",
      text: "Ein Industrial ist kaum zu übersehen – und genau das ist der Punkt. Frag, welches Barbell als Nächstes kommt oder wie der Alltag mit Kopfhörern und Mütze klappt. Kleine Frage, ehrliches Gespräch.",
    },
    hookLinkLabel: "Singles mit Ohrpiercings in deiner Nähe finden →",
    sceneLine: "Wer einen Industrial trägt, hat sich bewusst für auffällig entschieden. Bei Dich mit Stich ist das kein Thema, sondern ein guter Anfang.",
    pullQuote: "Das Industrial Piercing ist spezieller, da es eigentlich zwei Piercings beinhaltet.",
    related: ["helix-piercing", "orbital-piercing", "rook-piercing"],
  },
  "intimpiercing": {
    motif: "Intimpiercing",
    glanceTitle: "Intimpiercing: das Wichtigste",
    facts: [
      { label: "Bei Männern", items: ["Prinz Albert", "Frenum", "Ampallang", "Apadravya"] },
      { label: "Bei Frauen", items: ["Klitorisvorhaut", "Christina", "Schamlippen", "Nefertiti"] },
      { label: "Vorher klären", items: ["Passende Anatomie", "Seriöses Studio", "Pflegeaufwand"] },
    ],
    flirtHook: {
      title: "Eine Frage des Vertrauens",
      text: "Ein Intimpiercing ist Privatsache – und gehört dir allein. Ob du es jemals erwähnst, entscheidest du. Wer offen über Körperschmuck reden kann, findet leichter jemanden, bei dem Ehrlichkeit von Anfang an dazugehört.",
    },
    hookLinkLabel: "Aufgeschlossene Singles in deiner Nähe kennenlernen →",
    sceneLine: "Selbstbestimmt, auch beim Körperschmuck. Bei Dich mit Stich lernst du Singles kennen, die das respektieren.",
    pullQuote: "Intimpiercings sind für viele Menschen vor allem ein Thema rund um persönlichen Ausdruck, Schmuck und individuelle Vorlieben.",
    related: ["christina-piercing", "prinz-albert-piercing", "frenulum-piercing"],
  },
  "jestrum-piercing": {
    motif: "Jestrum",
    glanceTitle: "Jestrum-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Philtrum", "Oberlippe", "Lippenrot"] },
      { label: "Schmuck", items: ["Stecker", "Gerader Stab", "Bananabell"] },
      { label: "Passt zu", items: ["Voller Oberlippe", "Ausgeprägtem Amorbogen", "Individualisten"] },
    ],
    flirtHook: {
      title: "Liebeszauber über der Lippe",
      text: "Der wissenschaftliche Name des Philtrums bedeutet so viel wie „Liebeszauber“ – und genau dort sitzt das Jestrum-Piercing. Eine bessere Vorlage für den ersten Satz im Chat gibt es kaum.",
    },
    hookLinkLabel: "Individualisten mit Piercing in deiner Stadt finden →",
    sceneLine: "Neu, selten, bewusst gewählt – so ein Piercing verdient ein Gegenüber, das hinschaut. Bei Dich mit Stich triffst du Singles, die genau das tun.",
    pullQuote: "Ihr wissenschaftlicher Name bedeutet so viel wie „Liebeszauber“ – denn das Philtrum ist sehr empfänglich für Sinnesreize.",
    related: ["eskimo-piercing", "medusa-piercing", "lippenpiercing"],
  },
  "kinnpiercing": {
    motif: "Kinn",
    glanceTitle: "Kinnpiercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Kinnspitze", "Meist vertikal", "Surface-Piercing"] },
      { label: "Schmuck", items: ["Barbell", "Anfangs überlang", "Später kürzer"] },
      { label: "Vorher klären", items: ["Genug Hautgewebe", "Sauberes Studio", "Schmuckform", "Alltag mitdenken"] },
    ],
    flirtHook: {
      title: "Kinn hoch, Gespräch läuft",
      text: "Viele verwechseln das Kinnpiercing mit einem Labret – ein guter Moment, es besser zu wissen. Frag, wie oft der Unterschied schon erklärt werden musste. Aus kleinen Besserwisser-Momenten werden oft die lustigsten Dates.",
    },
    hookLinkLabel: "Singles mit Piercing in deiner Nähe finden →",
    sceneLine: "Ein Kinnpiercing ist eine bewusste Entscheidung für einen auffälligen Look. Bei Dich mit Stich zählt genau diese Konsequenz – leg dein Profil an und schau, wer ähnlich tickt.",
    pullQuote: "Beim Kinnpiercing geht es heute meist vor allem um die optische Wirkung.",
    related: ["labret-piercing", "mandible-piercing", "surface-piercing"],
  },
  "labret-piercing": {
    motif: "Labret",
    glanceTitle: "Labret-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Unterlippe", "Mittig", "Seitlich"] },
      { label: "Szene", items: ["Punk", "Techno", "Seit den 1990ern"] },
      { label: "Vorher klären", items: ["Hygienisches Studio", "Beratungsgespräch", "Stelle im Spiegel"] },
    ],
    flirtHook: {
      title: "Französisch oder englisch?",
      text: "Beim Labret gibt es zwei Aussprachen – und beide sind richtig. Frag einfach, wie sie oder er es sagt. Aus so einer Kleinigkeit wird schnell ein Gespräch über Punk, Techno und die ersten Konzerte.",
    },
    hookLinkLabel: "Singles mit Lippenpiercing in deiner Nähe →",
    sceneLine: "Das Labret gehört zu den Klassikern unter den Lippenpiercings. Bei Dich mit Stich ist es kein Hingucker für Fremde, sondern ein Grund, ins Gespräch zu kommen.",
    pullQuote: "Seit den 1990er-Jahren wird es regelmäßig gestochen und ist unter anderem nicht mehr aus der Punk- oder Technoszene wegzudenken.",
    related: ["lippenpiercing", "eskimo-piercing", "ashley-piercing"],
  },
  "lippenbandpiercing": {
    motif: "Lippenband",
    glanceTitle: "Lippenbandpiercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Lippenbändchen", "Innenseite Oberlippe", "Sichtbar beim Lächeln"] },
      { label: "Wirkt", items: ["Dezent", "Versteckt", "Individuell", "Betont das Lächeln"] },
      { label: "Vorher klären", items: ["Zähne & Zahnfleisch", "Abgeflachte Kugeln", "Essgewohnheiten"] },
    ],
    flirtHook: {
      title: "Erst beim Lächeln",
      text: "Ein Smiley-Piercing zeigt sich erst, wenn jemand lächelt. Wer es beim ersten Treffen entdeckt, hat also schon etwas richtig gemacht – und einen charmanten Gesprächseinstieg gleich dazu.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Nähe entdecken →",
    sceneLine: "Manche Details sieht man erst auf den zweiten Blick. Bei Dich mit Stich lernst du Singles kennen, die genau solche Details zu schätzen wissen.",
    pullQuote: "Wer nach einem eher dezenten Piercing sucht, findet hier oft eine auffällige, aber gleichzeitig versteckte Variante.",
    related: ["lippenpiercing", "zungenpiercing", "medusa-piercing"],
  },
  "lippenpiercing": {
    motif: "Lippe",
    glanceTitle: "Lippenpiercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Lippe", "Meist Unterlippe", "Mundbereich"] },
      { label: "Tradition", items: ["Afrika", "Süd-Amerika", "Alaska", "Religiöser Brauch"] },
      { label: "Vorher klären", items: ["Vorgespräch", "Seriöses Studio", "Wirkung im Alltag"] },
    ],
    flirtHook: {
      title: "Schmuck mit Geschichte",
      text: "In manchen Ländern wird das Lippenpiercing sogar als Ehering getragen. Ein charmanter Einstieg: Frag, ob es bei ihr oder ihm einfach Schmuck ist oder doch ein Stück mehr Bedeutung hat.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Stadt finden →",
    sceneLine: "Ein Lippenpiercing sieht jeder beim ersten Lächeln. Bei Dich mit Stich treffen sich Singles, für die das kein Thema ist, sondern ein Pluspunkt.",
    pullQuote: "Bei einigen Völkern ist das Schmücken der Unterlippe sogar ein religiöser Brauch.",
    related: ["labret-piercing", "ashley-piercing", "snakebite-piercing"],
  },
  "lobe-piercing": {
    motif: "Lobe",
    glanceTitle: "Lobe Piercing in 20 Sekunden",
    facts: [
      { label: "Varianten", items: ["Klassisch mittig", "Mehrere nebeneinander", "Gedehnt"] },
      { label: "Gestochen mit", items: ["Einwegnadel", "Im Piercingstudio", "Keine Pistole"] },
      { label: "Pflege", items: ["1–2 Mal täglich", "Nicht drehen", "Saubere Hände"] },
    ],
    flirtHook: {
      title: "Klassiker mit Seemannsgarn",
      text: "Schon Seeleute trugen Ohrschmuck mit eingravierten Initialen – das Lobe hat mehr Geschichte, als man ihm ansieht. Und wer seine Ohrlöcher gedehnt oder mehrfach gestochen hat, hat oft eine eigene Geschichte dazu.",
    },
    hookLinkLabel: "Singles mit Ohrschmuck in deiner Nähe entdecken →",
    sceneLine: "Das erste Ohrloch ist für viele der Anfang von allem. Bei Dich mit Stich lernst du Singles kennen, bei denen es nicht dabei geblieben ist.",
    pullQuote: "Denkt man an Piraten, fällt direkt die goldene Kreole ein.",
    related: ["flesh-tunnel", "helix-piercing", "ohrmuschel-piercing"],
  },
  "madonna-piercing": {
    motif: "Madonna",
    glanceTitle: "Madonna Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Seitlich über Lippe", "Oberlippe", "Platz des Schönheitsflecks"] },
      { label: "Inspiriert von", items: ["Madonna", "Marilyn Monroe", "Cindy Crawford", "Rayna Foss-Rose"] },
      { label: "Vorher klären", items: ["Seriöses Studio", "Schmuckmaterial", "Unverträglichkeiten"] },
    ],
    flirtHook: {
      title: "Der Schönheitsfleck 2.0",
      text: "Das Madonna Piercing ist aus dem berühmten Schönheitsfleck entstanden. Frag, welche Stilikone dahintersteckt – Madonna, Marilyn oder ganz jemand anderes. Über Vorbilder kommt man schnell auf Musik, Filme und den eigenen Stil.",
    },
    hookLinkLabel: "Singles mit Stil in deiner Nähe entdecken →",
    sceneLine: "Wer ein Madonna Piercing trägt, setzt bewusst ein Statement. Bei Dich mit Stich zeigen Singles ihren Stil – und finden Menschen, die ihn feiern.",
    pullQuote: "Wer seinen eigenen Stil kreiert, der setzt damit ein echtes Statement.",
    related: ["medusa-piercing", "labret-piercing", "lippenpiercing"],
  },
  "mandible-piercing": {
    motif: "Mandible",
    glanceTitle: "Mandible Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Unter der Zunge", "Austritt unterm Kinn", "Unterkiefer"] },
      { label: "Auch genannt", items: ["Sprung-Piercing", "Deep-Oral-Piercing", "Unterkiefer-Piercing"] },
      { label: "Wirkt", items: ["Exotisch", "Außergewöhnlich", "Selten", "Auffällig"] },
    ],
    flirtHook: {
      title: "Kein Auftritt ohne Blicke",
      text: "Mit einem Mandible Piercing betritt niemand unbemerkt einen Raum. Frag ruhig, wie es zu dieser Entscheidung kam – bei einem so seltenen Piercing ist das der naheliegende Einstieg.",
    },
    hookLinkLabel: "Extravagante Gepiercte in deiner Nähe entdecken →",
    sceneLine: "Wer gern im Mittelpunkt steht, braucht ein Gegenüber, das hinsieht statt wegzuschauen. Bei Dich mit Stich findest du Singles, die Körperkunst feiern.",
    pullQuote: "Wer mit diesem außergewöhnlichen Piercing einen Raum betritt, kann damit rechnen, dass sich alle Blicke auf ihn richten werden.",
    related: ["zungenpiercing", "kinnpiercing", "uvula-piercing"],
  },
  "medusa-piercing": {
    motif: "Medusa",
    glanceTitle: "Medusa Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Philtrum", "Über der Oberlippe", "Unter der Nase"] },
      { label: "Hintergrund", items: ["Akuntsu in Brasilien", "Friseur Carrick", "Name seit 1990"] },
      { label: "Vorher klären", items: ["Job mit Kundenkontakt", "Stecker aus Kunststoff", "Nicht für Anfänger"] },
    ],
    flirtHook: {
      title: "Ein kleiner Liebeszauber",
      text: "Der durchstochene Bereich heißt anatomisch auch Philton – was für Liebeszauber steht. Ein besseres Stichwort für den ersten Satz gibt es kaum. Frag, ob sie oder er das beim Stechen schon wusste.",
    },
    hookLinkLabel: "Singles mit Medusa & Co. in deiner Nähe →",
    sceneLine: "Ein Medusa Piercing will gesehen werden, und das ist auch gut so. Bei Dich mit Stich bist du unter Leuten, die genau hinschauen – aus den richtigen Gründen.",
    pullQuote: "Das Medusa Piercing wird gerne von Menschen gewählt, die den Wunsch haben, dass ein Piercing auch gesehen wird.",
    related: ["madonna-piercing", "eskimo-piercing", "ashley-piercing"],
  },
  "nasallang-piercing": {
    motif: "Nasallang",
    glanceTitle: "Nasallang-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Beide Nasenflügel", "Nasenscheidewand", "Gerader Barbell"] },
      { label: "Kombiniert", items: ["Zwei Nostrils", "Hohes Septum", "Eine Sitzung", "Oder mehrere Sitzungen"] },
      { label: "Hintergrund", items: ["Indien", "Kriegerische Tapferkeit", "Cliff Cadaver"] },
    ],
    flirtHook: {
      title: "Drei in einem",
      text: "Von außen sieht ein Nasallang oft aus wie zwei Nostrils – bis jemand genauer hinschaut. Frag nach dem Überraschungsmoment. Wer so ein Detail versteckt, freut sich meist, wenn es jemand entdeckt.",
    },
    hookLinkLabel: "Piercing-Fans in deiner Nähe entdecken →",
    sceneLine: "Das Nasallang ist eher etwas für piercing-affine Kreise. Genau die findest du bei Dich mit Stich – schau dich um, wer noch so denkt.",
    pullQuote: "Da es nur rechts und links an den Nasenflügeln zu sehen ist, wird es oft für zwei Nostril-Piercings gehalten: Perfekt für Überraschungsmomente.",
    related: ["nostril-piercing", "septum-piercing", "septril-piercing"],
  },
  "nostril-piercing": {
    motif: "Nostril",
    glanceTitle: "Nostril Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nasenflügel", "Einseitig", "Beidseitig", "Doppelt nebeneinander"] },
      { label: "Schmuck", items: ["Stecker", "Glitzerstein", "Breiter Ring"] },
      { label: "Hintergrund", items: ["Mittlerer Osten", "Indien", "Hippies & Punks"] },
    ],
    flirtHook: {
      title: "Klein, aber wandelbar",
      text: "Ein Nostril wechselt mit Laune und Anlass – mal dezenter Glitzerstein, mal breiter Ring. Frag, welcher Schmuck heute drin ist und warum. Kleine Stilentscheidungen verraten oft viel über die Stimmung des Tages.",
    },
    hookLinkLabel: "Singles mit Nasenpiercing in deiner Nähe →",
    sceneLine: "Das Nostril ist eines der beliebtesten Piercings überhaupt – und trotzdem ganz persönlich. Bei Dich mit Stich zeigen Singles ihren Stil im Profil.",
    pullQuote: "Bekannte Persönlichkeiten wie Lenny Kravitz ließen sich das Nostril stechen, wodurch es sich international etablierte.",
    related: ["septum-piercing", "nasallang-piercing", "bridge-piercing"],
  },
  "ohrmuschel-piercing": {
    motif: "Ohrmuschel",
    glanceTitle: "Ohrmuschel Piercing in 20 Sekunden",
    facts: [
      { label: "Varianten", items: ["Rook", "Helix", "Conch", "Tragus", "Daith"] },
      { label: "Wirkt", items: ["Individuell", "Auffällig", "Schmückt das Ohr"] },
      { label: "Vorher klären", items: ["Position am Ohr", "Studio & Beratung", "Schmuckauswahl", "Nachsorge"] },
    ],
    flirtHook: {
      title: "Jedes Ohr ein Unikat",
      text: "Keine Ohrmuschel gleicht der anderen, und so ist auch jedes Piercing darin ein bisschen eigen. Frag, welche Variante es geworden ist und warum – Rook, Helix oder Conch sind ein leichter Einstieg ins Gespräch.",
    },
    hookLinkLabel: "Singles mit Ohrpiercings in deiner Nähe entdecken →",
    sceneLine: "Ohrschmuck ist oft das Erste, was beim Kennenlernen auffällt. Bei Dich mit Stich darf er ruhig mehr sein als ein Detail.",
    pullQuote: "Die Ohrmuschel ist ein einzigartiges Körperteil, das durch ein Piercing gekonnt in Szene gesetzt werden kann.",
    related: ["helix-piercing", "conch-piercing", "rook-piercing"],
  },
  "orbital-piercing": {
    motif: "Orbital",
    glanceTitle: "Orbital-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Helix", "Conch", "Lobe", "Rook", "Tragus"] },
      { label: "Schmuck", items: ["Klemmkugelringe", "Segmentringe", "D-Ringe", "Twister"] },
      { label: "Vorher klären", items: ["Schmuck zuerst wählen", "Lochabstand", "Stechen oder Punchen"] },
    ],
    flirtHook: {
      title: "Ein Ring, zwei Löcher",
      text: "Saturn-Ring oder Raketenbahn – das Orbital hat einen Namen, der nach einer Geschichte fragt. Wer weiß, warum es genau an dieser Stelle des Ohrs sitzt, hat den Gesprächseinstieg schon in der Hand.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Nähe entdecken →",
    sceneLine: "Ein Orbital fällt nur denen auf, die genau hinschauen. Bei Dich mit Stich schauen Singles genau hin – und zeigen ihren Schmuck gern im Profil.",
    pullQuote: "Seinen Namen hat das Orbital-Piercing von der optischen Ähnlichkeit mit elliptischen Umlaufbahnen erhalten.",
    related: ["industrial-piercing", "helix-piercing", "conch-piercing"],
  },
  "penispiercing": {
    motif: "Penispiercing",
    glanceTitle: "Penispiercing: das Wichtigste",
    facts: [
      { label: "Varianten", items: ["Prinz Albert", "Ampallang", "Apadravya", "Dydoe", "Frenulum"] },
      { label: "Sitzt an", items: ["Eichel", "Penisschaft", "Vorhaut", "Hodensack"] },
      { label: "Vorher klären", items: ["Erfahrener Piercer", "Hygiene", "Pflege"] },
    ],
    flirtHook: {
      title: "Kein Thema fürs erste Hallo",
      text: "Ein Penispiercing ist sehr persönlich und muss nicht im Profil stehen. Wer aber offen mit dem eigenen Körper umgeht, wünscht sich meist ein Gegenüber, das Offenheit schätzt – wann welches Gespräch passt, entscheidet ihr gemeinsam.",
    },
    hookLinkLabel: "Offene Singles aus deiner Stadt entdecken →",
    sceneLine: "Dein Körper, deine Entscheidung. Bei Dich mit Stich triffst du Singles, die Körperschmuck mit Respekt begegnen.",
    pullQuote: "Die wesentliche Motivation für das Stechen eines Intimpiercings ist – wie auch bei allen anderen Piercings – die Individualisierung des eigenen Körpers.",
    related: ["prinz-albert-piercing", "frenulum-piercing", "intimpiercing"],
  },
  "prinz-albert-piercing": {
    motif: "Prinz Albert",
    glanceTitle: "Prinz-Albert-Piercing: das Wichtigste",
    facts: [
      { label: "Auch genannt", items: ["PA", "Prince Albert"] },
      { label: "Sitzt an", items: ["Eichel", "Durch die Harnröhre"] },
      { label: "Schmuck", items: ["Ball Closure Ring", "Hufeisen", "Banana Bell"] },
    ],
    flirtHook: {
      title: "Königlicher Name, private Sache",
      text: "Die Legende um Prinz Albert, den Ehemann von Königin Victoria, ist eine gute Anekdote für jede Runde. Das Piercing selbst bleibt deine Sache – und wem du davon erzählst, entscheidest allein du.",
    },
    hookLinkLabel: "Offene Singles aus deiner Nähe kennenlernen →",
    sceneLine: "Körperschmuck ist bei Dich mit Stich kein Tabu, sondern Teil der Persönlichkeit. Hier triffst du Singles, die offen und respektvoll damit umgehen.",
    pullQuote: "Den besonderen Namen hat das Piercing von dem namensgleichen ersten Träger Prinz Albert, dem Ehemann von Königin Victoria von England.",
    related: ["frenulum-piercing", "penispiercing", "intimpiercing"],
  },
  "rook-piercing": {
    motif: "Rook",
    glanceTitle: "Rook Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Antihelix", "Kleine Knorpelfalte", "Ohrmuschel"] },
      { label: "Wirkt", items: ["Auffällig", "Eher dezent", "Persönlicher Stil"] },
      { label: "Vorher klären", items: ["Seriöses Studio", "Kopfhörer", "Schlafseite", "Pflege"] },
    ],
    flirtHook: {
      title: "Ein Name mit Geschichte",
      text: "Rook war der Spitzname des kalifornischen Piercers Eric Dakota, der den Begriff Anfang der 90er mit diesem Piercing verband. Wer so eine Anekdote parat hat, braucht keine Anmachsprüche.",
    },
    hookLinkLabel: "Gepiercte Singles aus deiner Stadt kennenlernen →",
    sceneLine: "Ein Rook sieht man erst, wenn man genau hinschaut. Bei Dich mit Stich schauen Singles genau hin – auf Piercings, Tattoos und die Menschen dahinter.",
    pullQuote: "Für viele ist es vor allem eine Frage des persönlichen Stils, denn das Piercing fällt auf, wirkt aber gleichzeitig eher dezent als große Ohrschmuck-Variante.",
    related: ["daith-piercing", "helix-piercing", "conch-piercing"],
  },
  "septril-piercing": {
    motif: "Septril",
    glanceTitle: "Septril Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nasenscheidewand", "Gedehntes Septum", "Durch den Knorpel"] },
      { label: "Auch genannt", items: ["Dschungelpiercing", "Nasenpiercing-Sonderform", "Sehr selten"] },
      { label: "Vorher klären", items: ["Septum vorhanden", "Lange Dehnung", "Viel Geduld", "Gespräch mit Arzt"] },
    ],
    flirtHook: {
      title: "Geduld als Statement",
      text: "Bis zum Septril vergehen etwa 18 Monate Dehnung – das macht niemand aus einer Laune heraus. Frag, was während dieser langen Zeit durchgehalten hat. Wer so dranbleibt, weiß meist auch sonst, was er will.",
    },
    hookLinkLabel: "Stark gepiercte Singles in deiner Nähe →",
    sceneLine: "Selbst unter Gepiercten hat kaum jemand ein Septril. Bei Dich mit Stich triffst du Menschen, die wissen, was hinter so einem Weg steckt.",
    pullQuote: "Der Lohn hierfür ist ein Piercing, das nicht nur besonders schön anzusehen ist – es ist selbst unter Piercingliebhabern ein Piercing, das auffällt.",
    related: ["septum-piercing", "nasallang-piercing", "flesh-tunnel"],
  },
  "septum-piercing": {
    motif: "Septum",
    glanceTitle: "Septum-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nasenscheidewand", "Dünnes Häutchen", "Nasenmitte"] },
      { label: "Schmuck", items: ["Ring", "Stab", "Bananenstecker", "Hufeisen-Ring", "Fake-Septum"] },
      { label: "Hintergrund", items: ["Mayas & Azteken", "Kriegerschmuck", "Initiations-Rituale", "Afrika & Asien"] },
    ],
    flirtHook: {
      title: "Uralt und trotzdem jetzt",
      text: "Ein Septum trugen schon Krieger und Mayas – heute ist es ein Statement mitten im Gesicht. Frag, ob der Ring im Alltag sichtbar bleibt oder auch mal nach innen gedreht wird. Daraus wird schnell ein Gespräch über Job, Freiheit und Stil.",
    },
    hookLinkLabel: "Singles mit Septum in deiner Nähe entdecken →",
    sceneLine: "Wer ein Septum trägt, kennt die immer gleichen Sprüche längst auswendig. Bei Dich mit Stich triffst du Singles, die lieber nach der Geschichte dahinter fragen.",
    pullQuote: "Schon die Mayas und die Azteken trugen aus religiösen Gründen einen Nasenring.",
    related: ["nostril-piercing", "septril-piercing", "nasallang-piercing"],
  },
  "snake-eyes-piercing": {
    motif: "Snake Eyes",
    glanceTitle: "Snake Eyes Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Zungenspitze", "Horizontal gestochen", "Links nach rechts"] },
      { label: "Wirkt", items: ["Hingucker", "Selten", "Wie Schlangenaugen"] },
      { label: "Vorher klären", items: ["Risiken abwägen", "Erfahrenes Studio", "Eigene Mundsituation", "Pflegehinweise"] },
    ],
    flirtHook: {
      title: "Blick auf die Zungenspitze",
      text: "Snake Eyes zeigt sich meist erst im Gespräch oder beim Lachen. Frag ruhig, was hinter der Entscheidung steckt – bei einer so seltenen Variante des Zungenpiercings lohnt sich die Frage.",
    },
    hookLinkLabel: "Singles mit Zungenpiercing in deiner Nähe kennenlernen →",
    sceneLine: "Schlangenaugen sind nicht jedermanns Sache – bei Dich mit Stich triffst du Singles, die das Besondere suchen statt das Übliche.",
    pullQuote: "Mit dem besonderen Aussehen wollen sich vor allem junge Leute von den anderen unterscheiden.",
    related: ["zungenpiercing", "venom-piercing", "snakebite-piercing"],
  },
  "snakebite-piercing": {
    motif: "Snakebite",
    glanceTitle: "Snakebite Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Unter der Unterlippe", "Links und rechts", "Symmetrisch"] },
      { label: "Wirkt", items: ["Markant", "Klar geordnet", "Extravagant", "Hingucker"] },
      { label: "Vorher klären", items: ["Erfahrener Piercer", "Material", "Sterilität", "Nachsorge"] },
    ],
    flirtHook: {
      title: "Zwei Punkte, ein Biss",
      text: "Snakebites fallen sofort auf – und liefern die erste Frage gleich mit: Warum gerade der Schlangenbiss? Die Antwort verrät oft, wie viel Stil hinter der Symmetrie steckt.",
    },
    hookLinkLabel: "Singles mit Lippenpiercing in deiner Stadt finden →",
    sceneLine: "Wer Snakebites trägt, kennt die Blicke. Bei Dich mit Stich sind sie kein Grund zum Tuscheln, sondern ein Grund zum Anschreiben.",
    pullQuote: "Durch die symmetrische Platzierung wirkt der Schmuck auffällig, aber zugleich klar geordnet.",
    related: ["lippenpiercing", "labret-piercing", "medusa-piercing"],
  },
  "surface-piercing": {
    motif: "Surface",
    glanceTitle: "Surface Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Nacken", "Hals", "Ebene Hautstellen"] },
      { label: "Methoden", items: ["Stechen", "Punchen"] },
      { label: "Vorher klären", items: ["Reibung durch Kleidung", "Alltag", "Beratung im Studio"] },
    ],
    flirtHook: {
      title: "Schmuck auf der Oberfläche",
      text: "Ein Surface Piercing im Nacken sieht man oft erst, wenn jemand die Haare hochnimmt. Solche Details machen neugierig – und eine Frage nach der Stelle ist ein unaufdringlicher Weg ins Gespräch.",
    },
    hookLinkLabel: "Singles mit Body Mods in deiner Nähe finden →",
    sceneLine: "Ein Surface Piercing ist gut geplant und bewusst gesetzt. Bei Dich mit Stich findest du Singles, die solche Entscheidungen verstehen.",
    pullQuote: "Vor einem Surface Piercing lohnt sich eine ruhige Abwägung.",
    related: ["deep-chest-piercing", "bauchnabelpiercing", "christina-piercing"],
  },
  "tragus-piercing": {
    motif: "Tragus",
    glanceTitle: "Tragus-Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Tragus", "Vor dem Gehörgang", "Kleiner Knorpel"] },
      { label: "Wirkt", items: ["Selten", "Individuell", "Eher zurückhaltend"] },
      { label: "Beliebt bei", items: ["Rock-Fans", "Pop-Fans", "Jungen Menschen"] },
    ],
    flirtHook: {
      title: "Griechisch für Ziegenbock",
      text: "Tragus kommt aus dem Altgriechischen und bedeutet Ziegenbock. Mit dieser Info bringst du Tragus-Träger im Chat wahrscheinlich eher zum Schmunzeln als mit jedem Standard-Hallo.",
    },
    hookLinkLabel: "Gepiercte Singles in deiner Nähe treffen →",
    sceneLine: "Ein Tragus-Piercing weckt Neugier. Bei Dich mit Stich darf aus Neugier ruhig mehr werden.",
    pullQuote: "Das Tragus-Piercing ist eine besondere Form des Ohrpiercings, die vor allem durch ihre Lage und ihren auffälligen, aber dennoch eher dezenten Look interessant ist.",
    related: ["helix-piercing", "daith-piercing", "conch-piercing"],
  },
  "uvula-piercing": {
    motif: "Uvula",
    glanceTitle: "Uvula Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Gaumenzäpfchen", "Im Mundraum", "Oralpiercing"] },
      { label: "Schmuck & Technik", items: ["Ball Closure Ring", "Gebogene Nadel", "Schneller Vorgang"] },
      { label: "Vorher klären", items: ["Erfahrener Piercer", "Ablauf", "Nachsorge", "Mundhygiene"] },
    ],
    flirtHook: {
      title: "Schmuck im Verborgenen",
      text: "Ein Uvula Piercing sieht man nicht im Vorbeigehen – davon erfährt man. Wenn dir jemand davon erzählt, ist das ein kleiner Vertrauensbeweis und ziemlich guter Stoff für das nächste Gespräch.",
    },
    hookLinkLabel: "Singles mit besonderem Körperschmuck in deiner Stadt →",
    sceneLine: "Nicht jeder Schmuck ist auf den ersten Blick zu sehen. Bei Dich mit Stich zählt, wer du bist – samt der Details, die nur Eingeweihte kennen.",
    pullQuote: "Man möchte seinen Körper so zeigen, wie man ihn selbst liebt.",
    related: ["zungenpiercing", "lippenbandpiercing", "mandible-piercing"],
  },
  "venom-piercing": {
    motif: "Venom",
    glanceTitle: "Venom Piercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Zunge", "Links und rechts", "Symmetrisch"] },
      { label: "Wirkt", items: ["Extravagant", "Ausgefallen", "Auffällig"] },
      { label: "Vorher klären", items: ["Erfahrenes Studio", "Platzierung", "Ein, zwei Termine", "Pflege"] },
    ],
    flirtHook: {
      title: "Doppelt hält besser",
      text: "Zwei Barbells durch die Zunge wählt niemand nebenbei. Frag, ob beide Hälften an einem Tag gestochen wurden oder in zwei Terminen – schon seid ihr mitten in einem Gespräch über Mut, Geduld und Stil.",
    },
    hookLinkLabel: "Mutige Gepiercte in deiner Stadt kennenlernen →",
    sceneLine: "Wer ein Venom Piercing trägt, hat keine Angst vor Blicken. Bei Dich mit Stich zeigen Singles im Profil, was sie ausmacht.",
    pullQuote: "Das Venom Piercing ist eine spezielle Art der Körpermodifikation und sticht vor allem durch seine Extravaganz und Ausgefallenheit heraus.",
    related: ["zungenpiercing", "snake-eyes-piercing", "snakebite-piercing"],
  },
  "zungenpiercing": {
    motif: "Zunge",
    glanceTitle: "Zungenpiercing in 20 Sekunden",
    facts: [
      { label: "Sitzt an", items: ["Durch die Zunge", "Im Mundraum", "Dezent verborgen"] },
      { label: "Geschichte", items: ["Azteken", "Aborigines", "Horst Streckenbach", "90er Jahre"] },
      { label: "Vorher klären", items: ["Erfahrener Piercer", "Hygiene", "Zähne schützen"] },
    ],
    flirtHook: {
      title: "Versteckt, aber gesprächig",
      text: "Ein Zungenpiercing sieht man oft erst beim Reden oder Lachen. Viele Träger finden es angenehm beim Küssen – die Frage danach hebst du dir aber lieber fürs zweite Date auf.",
    },
    hookLinkLabel: "Singles mit Zungenpiercing in deiner Nähe entdecken →",
    sceneLine: "Ein Zungenpiercing verrät sich erst im Gespräch. Bei Dich mit Stich beginnt genau dieses Gespräch – mit Singles, denen du dein Piercing nicht erklären musst.",
    pullQuote: "In der Gegenwart wird das Zungenpiercing im westlichen Kulturkreis vor allem als Schmuckstück benutzt.",
    related: ["snake-eyes-piercing", "venom-piercing", "lippenbandpiercing"],
  },
};
