/**
 * Curated extras for the tattoo articles: editorial copy that sits around the unchanged WordPress
 * text. Articles without a profile fall back to what their own text names (see tattoo-motifs.ts).
 */
export type TattooMotifProfile = {
  motif: string;
  glanceTitle: string;
  facts: readonly { label: string; items: readonly string[] }[];
  flirtHook: { title: string; text: string };
  hookLinkLabel: string;
  sceneLine: string;
  /** A sentence from the article itself, so the highlighted quote never says more than the text. */
  pullQuote: string;
  related: readonly string[];
};

export const TATTOO_MOTIF_PROFILES: Record<string, TattooMotifProfile> = {
  "afrikanische-tribal-tattoo": {
    motif: "Afrikanisches Tribal",
    glanceTitle: "Afrikanisches Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Herkunft", "Mut", "Spiritualität", "Zugehörigkeit"] },
      { label: "Typische Elemente", items: ["Geometrische Formen", "Wiederkehrende Muster", "Starke Kontraste"] },
      { label: "Vorher klären", items: ["Motivation", "Symbolik prüfen", "Ethno-erfahrener Artist"] },
    ],
    flirtHook: {
      title: "Muster mit Geschichte",
      text: "Hinter geometrischen Tribals steckt oft die Frage: Geht es um die Grafik oder um eine Bedeutung? Genau das ist ein schöner Einstieg – ehrlich neugierig gefragt, ohne gleich selbst zu deuten.",
    },
    hookLinkLabel: "Singles mit Tattoos in deiner Stadt entdecken →",
    sceneLine: "Wer ein Motiv mit Bedacht wählt, sucht meist auch beim Kennenlernen mehr als Oberfläche. Dich mit Stich ist der Ort für Singles, die ihre Tattoos mit Überzeugung tragen.",
    pullQuote: "Afrikanisch inspirierte Tribal-Motive sollten nicht als einheitlicher Stil verstanden werden.",
    related: ["tribal-tattoo", "borneo-tribal-tattoo", "hawaiianische-tribal-tattoo"],
  },
  "animal-sleeve-tattoo": {
    motif: "Animal Sleeve",
    glanceTitle: "Animal Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Tiere", items: ["Wolf", "Löwe", "Eule", "Schlange"] },
      { label: "Steht für", items: ["Stärke", "Weisheit", "Freiheit", "Schutz", "Mut"] },
      { label: "Oft kombiniert mit", items: ["Blumen", "Geometrie", "Florale Akzente"] },
    ],
    flirtHook: {
      title: "Welches Tier bist du?",
      text: "Wolf, Eule oder Schlange – jedes Tier auf dem Arm steht für etwas. Frag, welches im Mittelpunkt steht und warum. Die Antwort sagt oft viel darüber, was deinem Gegenüber wichtig ist.",
    },
    hookLinkLabel: "Tätowierte Tierfans in deiner Nähe entdecken →",
    sceneLine: "Stärke, Schutz, Weisheit – dein Sleeve hat eine klare Botschaft. Bei Dich mit Stich findest du Menschen, die sie lesen können.",
    pullQuote: "Entscheidend ist dabei nicht nur die Bedeutung der einzelnen Tiere, sondern auch, wie Stil, Größenverhältnis und Kontraste miteinander harmonieren.",
    related: ["wolf-tattoo", "vogel-tattoos", "neo-traditional-sleeve-tattoo"],
  },
  "anker-tattoos": {
    motif: "Anker",
    glanceTitle: "Anker Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Heimat", "Hoffnung", "Halt", "Treue", "Große Liebe"] },
      { label: "Beliebt auf", items: ["Oberarm", "Wade", "Handgelenk", "Knöchel", "Finger"] },
      { label: "Typische Stile", items: ["Oldschool", "Minimalistisch", "Dot Work", "Watercolor"] },
    ],
    flirtHook: {
      title: "Wer ist dein Hafen?",
      text: "Ein Anker steht oft für einen Menschen, zu dem man immer zurückkehrt. Frag ruhig, wer oder was damit gemeint ist – Heimat, Familie, Freunde oder die große Liebe. Das Gespräch geht selten an der Oberfläche vorbei.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Du suchst jemanden, bei dem du ankommen kannst? Bei Dich mit Stich treffen sich Singles, für die Tattoos zur Geschichte gehören.",
    pullQuote: "Sie waren wie ein Kompass, welcher fest in der Haut verankert war und sie stets gesund und munter nach Hause bringen sollte.",
    related: ["old-school-tattoos", "liebes-tattoo", "partner-tattoos"],
  },
  "aztekische-maya-tribal-tattoo": {
    motif: "Aztekisches & Maya Tribal",
    glanceTitle: "Azteken- & Maya-Tattoo in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Götter", "Kalenderzeichen", "Kriegersymbole"] },
      { label: "Steht für", items: ["Macht", "Schutz", "Mut", "Ewigkeit"] },
      { label: "Vorher klären", items: ["Symbolik verstehen", "Genug Fläche", "Mehrere Sitzungen"] },
    ],
    flirtHook: {
      title: "Mythen als Gesprächsstoff",
      text: "Götter, Kalenderzeichen, Kriegersymbole – solche Motive haben fast immer eine Vorgeschichte. Frag, welches Zeichen gewählt wurde und warum. Oft landet ihr schnell bei Reisen, Geschichte oder dem, was jemandem Kraft gibt.",
    },
    hookLinkLabel: "Tätowierte in deiner Nähe kennenlernen →",
    sceneLine: "Ein detailreiches Großprojekt braucht Geduld – das Kennenlernen darf leichter sein. Bei Dich mit Stich stößt dein Motiv auf echtes Interesse statt auf Stirnrunzeln.",
    pullQuote: "Sie zeigen Götter, Kalenderzeichen und Kriegersymbole – Ausdruck von Macht, Schutz und spiritueller Energie.",
    related: ["tribal-tattoo", "mythology-sleeve-tattoo", "afrikanische-tribal-tattoo"],
  },
  "biomechanical-sleeve-tattoo": {
    motif: "Biomechanical Sleeve",
    glanceTitle: "Biomechanical Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Zahnräder", "Pistons", "Metallstrukturen", "Aufgerissene Haut"] },
      { label: "Wirkt", items: ["Futuristisch", "Kraftvoll", "3D-Optik"] },
      { label: "Darauf achten", items: ["Klare Hauptidee", "Armverlauf folgen", "Einheitliche Schatten"] },
    ],
    flirtHook: {
      title: "Mensch trifft Maschine",
      text: "Ein Arm, unter dessen Haut scheinbar Zahnräder arbeiten, zieht Blicke an. Frag, wie die Idee entstanden ist und was genau an der Verbindung von Haut und Maschine reizt.",
    },
    hookLinkLabel: "Biomech-Fans in deiner Nähe entdecken →",
    sceneLine: "Zahnräder unter der Haut sind nicht jedermanns Sache – aber genau deine. Bei Dich mit Stich suchst du unter Menschen, die so einen Arm zu schätzen wissen.",
    pullQuote: "Typisch für diesen Stil ist das Zusammenspiel aus technischen Formen, räumlicher Tiefe und dem Eindruck, als würden mechanische Elemente unter der Haut sichtbar werden.",
    related: ["tattoo-stile", "skull-fire-sleeve-tattoo", "portrait-realism-sleeve-tattoo"],
  },
  "black-grey-sleeve-tattoo": {
    motif: "Black & Grey Sleeve",
    glanceTitle: "Black & Grey Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Totenkopf", "Rose", "Uhr", "Engelsfiguren"] },
      { label: "Steht für", items: ["Vergänglichkeit", "Liebe", "Zeit"] },
      { label: "Wirkt", items: ["Zeitlos", "Kontrastreich", "Elegant", "Ausdrucksstark"] },
    ],
    flirtHook: {
      title: "Zeitlos, nicht farblos",
      text: "Totenkopf, Rose und Uhr stehen für Vergänglichkeit, Liebe und Zeit – drei Themen, über die man ziemlich gut reden kann. Frag, welches davon für dein Gegenüber den Anfang gemacht hat.",
    },
    hookLinkLabel: "Black-&-Grey-Fans in deiner Nähe finden →",
    sceneLine: "Ein Black & Grey Sleeve braucht keine Farbe, um aufzufallen. Bei Dich mit Stich triffst du Singles, die feine Schattierungen genauso zu schätzen wissen wie du.",
    pullQuote: "Mit feinen Schattierungen entstehen Motive wie Totenköpfe, Rosen, Uhren oder Engelsfiguren, die sich zu einem stimmigen Full-Arm-Design verbinden.",
    related: ["skull-fire-sleeve-tattoo", "portrait-realism-sleeve-tattoo", "sleeve-tattoo"],
  },
  "blumen-tattoos": {
    motif: "Blumen",
    glanceTitle: "Blumen Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Lebensfreude", "Liebe", "Erinnerung", "Vergänglichkeit"] },
      { label: "Beliebte Blüten", items: ["Rose", "Lotus", "Kirschblüte", "Lavendel", "Pusteblume"] },
      { label: "Beliebt auf", items: ["Unterarm", "Nacken", "Schulter", "Bein"] },
    ],
    flirtHook: {
      title: "Durch die Blume gesagt",
      text: "Jede Blüte hat ihre eigene Sprache – die rote Rose etwas anderes als die Pusteblume. Frag, welche Blume es ist und woran sie erinnert. Oft verbindet der Mensch dahinter einen ganz persönlichen Moment damit.",
    },
    hookLinkLabel: "Singles mit Blumen-Tattoo in deiner Nähe entdecken →",
    sceneLine: "Zart, bunt oder schwarz-weiß – jedes florale Motiv erzählt etwas. Bei Dich mit Stich zeigst du deine Tattoos und lernst Menschen kennen, die genau hinschauen.",
    pullQuote: "Oft kommt es auch auf die Bedeutung oder Erinnerung an, die der jeweilige Tattoo-Träger mit der Blume auf seiner Haut verbindet.",
    related: ["floral-sleeve-tattoo", "frauen-tattoos", "mandala-tattoo"],
  },
  "borneo-tribal-tattoo": {
    motif: "Borneo Tribal",
    glanceTitle: "Borneo Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Herkunft", items: ["Dayak-Völker", "Borneo", "Alte Traditionen"] },
      { label: "Steht für", items: ["Schutz", "Stärke", "Natur & Ahnen"] },
      { label: "Typische Elemente", items: ["Symmetrische Ornamente", "Starke Kontraste", "Klare Linien"] },
    ],
    flirtHook: {
      title: "Ruhe mit Wucht",
      text: "Borneo-Tribals wirken still und kraftvoll zugleich. Ein guter Einstieg: Soll das Motiv traditionell wirken oder nur davon inspiriert sein? Wer darüber nachgedacht hat, erzählt gern, wie er zu seinem Stil gefunden hat.",
    },
    hookLinkLabel: "Singles mit Tribal-Tattoos in deiner Nähe →",
    sceneLine: "Symmetrie, Schwarz, Statement – und trotzdem kein Klischee. Bei Dich mit Stich findest du Leute, die solche Details auf den ersten Blick erkennen.",
    pullQuote: "Viele Muster werden mit Schutz, Stärke und der Verbindung zu Natur und Ahnen in Verbindung gebracht – gestochen in markanten, symmetrischen Formen.",
    related: ["tribal-tattoo", "polynesische-tribal-tattoo", "afrikanische-tribal-tattoo"],
  },
  "cover-up-tattoos": {
    motif: "Cover-up",
    glanceTitle: "Cover-up auf einen Blick",
    facts: [
      { label: "Gut geeignet", items: ["Japanisch", "Traditional", "Neo-traditional", "Biomechanik"] },
      { label: "Eher schwierig", items: ["Filigrane Stile", "Pastell-Watercolor", "Sehr dunkle Altlasten"] },
      { label: "Alternativen", items: ["Laser-Aufhellung", "Blast-over", "Auffrischen", "Schwarze Flächen"] },
    ],
    flirtHook: {
      title: "Zweite Chance, bessere Story",
      text: "Hinter fast jedem Cover-up steckt ein Vorher-Motiv. Frag ruhig, was darunter liegt – die Antwort ist meist lustig, manchmal ehrlich und immer ein guter Gesprächsstoff.",
    },
    hookLinkLabel: "Cover-up-Fans in deiner Nähe entdecken →",
    sceneLine: "Aus Tattoo-Fail wird Kunstwerk – und aus einer Nachricht vielleicht mehr. Bei Dich mit Stich sind Singles, die über ihre Tattoo-Geschichte gern lachen.",
    pullQuote: "Diese Tattoorettung ist nicht ohne Grund die Königsdisziplin der Tätowierkunst.",
    related: ["tattoo-entfernen", "japanische-tattoos", "tattoo-studio"],
  },
  "das-wikinger-tattoo": {
    motif: "Wikinger",
    glanceTitle: "Wikinger Tattoo in 20 Sekunden",
    facts: [
      { label: "Beliebte Symbole", items: ["Yggdrasil", "Runen", "Odin", "Trollkreuz", "Knotenmuster"] },
      { label: "Steht für", items: ["Nordische Mythologie", "Schutz", "Glaube", "Verbundenheit"] },
      { label: "Beliebt auf", items: ["Arm", "Wade", "Schulter", "Brust"] },
    ],
    flirtHook: {
      title: "Runen lesen lernen",
      text: "Ob Yggdrasil, Odin oder eine Reihe Runen – nordische Motive stecken voller Mythologie. Lass dir erklären, was die Zeichen bedeuten und warum es genau diese wurden. Wer gern erzählt, freut sich über echtes Interesse.",
    },
    hookLinkLabel: "Nordisch Tätowierte in deiner Nähe entdecken →",
    sceneLine: "Mythen auf der Haut, aber Lust auf eine Geschichte im Hier und Jetzt? Bei Dich mit Stich findest du Singles, die deine Motive nicht erst erklärt bekommen müssen.",
    pullQuote: "Denn bei den Wikingern handelte es sich um ein Volk mit einer äußerst originellen Kultur, welche die Menschen noch bis heute fasziniert und in ihren Bann zieht.",
    related: ["mythology-sleeve-tattoo", "wolf-tattoo", "tattoos-fuer-maenner"],
  },
  "erste-tattoo-stechen-lassen": {
    motif: "Erstes Tattoo",
    glanceTitle: "Erstes Tattoo: das Wichtigste",
    facts: [
      { label: "Vorher klären", items: ["Motiv & Skizze", "Körperstelle", "Studio & Hygiene", "Kosten & Anzahlung"] },
      { label: "Eher angenehm", items: ["Oberarm außen", "Schulter", "Po"] },
      { label: "Eher schmerzhaft", items: ["Brust", "Hüfte", "Fuß"] },
    ],
    flirtHook: {
      title: "Weißt du noch, dein erstes?",
      text: "Das erste Tattoo vergisst niemand – samt Nervosität im Studio. Frag nach dem ersten Motiv und wie der Termin war: Die Antwort ist fast immer eine gute Geschichte.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Erstes Tattoo geplant oder schon frisch gestochen? Bei Dich mit Stich bist du willkommen, egal ob mit einem Motiv oder mit ganzen Armen voller Tinte.",
    pullQuote: "Man muss sich darüber im Klaren sein, dass das Tattoo ein lebenslanger Begleiter sein wird und man es ständig auf dem Körper tragen wird.",
    related: ["tattoo-studio", "tattoo-motive", "wie-gefaehrlich-tattoo"],
  },
  "floral-sleeve-tattoo": {
    motif: "Floral Sleeve",
    glanceTitle: "Floral Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Blüten", items: ["Rosen", "Pfingstrosen", "Lotus", "Blätter"] },
      { label: "Wirkt", items: ["Elegant", "Harmonisch", "Zeitlos", "Unisex"] },
      { label: "Stil", items: ["Black & Grey", "Sanfte Farben", "Feine Schattierungen"] },
    ],
    flirtHook: {
      title: "Blüten mit Bedeutung",
      text: "Rose, Pfingstrose oder Lotus – kaum jemand wählt seine Blüten zufällig. Frag, welche Blume zuerst auf den Arm kam und warum. Das ist ein leichter Einstieg, der trotzdem Persönliches öffnet.",
    },
    hookLinkLabel: "Floral-Fans in deiner Nähe finden →",
    sceneLine: "Ein Floral Sleeve ist mehr als hübsche Deko. Bei Dich mit Stich treffen sich Singles, die auch bei Blüten nach der Geschichte fragen.",
    pullQuote: "Gerade Rosen und weiche Blattformen sorgen oft für eine ruhige Gesamtwirkung, die sowohl auffällig als auch ausgewogen wirken kann.",
    related: ["blumen-tattoos", "watercolor-sleeve-tattoo", "black-grey-sleeve-tattoo"],
  },
  "frauen-tattoos": {
    motif: "Tattoos für Frauen",
    glanceTitle: "Tattoos für Frauen auf einen Blick",
    facts: [
      { label: "Motiv-Ideen", items: ["Blumenmuster", "Lieblingstier", "Sprüche", "Namen der Kinder", "Musiknoten"] },
      { label: "Beliebte Stellen", items: ["Knöchel", "Hüfte", "Nacken", "Rücken", "Oberarm"] },
      { label: "Vorher klären", items: ["Sichtbarkeit", "Größe", "Alltag & Beruf", "Erweiterbarkeit"] },
    ],
    flirtHook: {
      title: "Motiv mit Charakter",
      text: "Ob Blumenranke oder Gitarre – ein gut gewähltes Tattoo passt zur Persönlichkeit. Frag, warum sie sich für genau dieses Motiv und diese Stelle entschieden hat, und du erfährst mehr als nur Geschmack.",
    },
    hookLinkLabel: "Tätowierte Frauen in deiner Nähe kennenlernen →",
    sceneLine: "Dein Tattoo unterstreicht, wer du bist. Bei Dich mit Stich zeigst du es im Profil – und triffst Menschen, die genau das an dir mögen.",
    pullQuote: "Ein Tattoo wirkt am besten, wenn es Deinen Charakter unterstreicht und Du Dich damit langfristig wohlfühlst.",
    related: ["tattoos-fuer-maenner", "blumen-tattoos", "erste-tattoo-stechen-lassen"],
  },
  "freundschaftstattoo": {
    motif: "Freundschaftstattoo",
    glanceTitle: "Freundschaftstattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Verbundenheit", "Gemeinsame Erinnerung", "Freundschaft"] },
      { label: "Beliebt auf", items: ["Handgelenk", "Arm", "Fuß", "Finger", "Schulter"] },
      { label: "Vorher klären", items: ["Motiv für beide", "Sichtbarkeit", "Größe", "Pflege"] },
    ],
    flirtHook: {
      title: "Mit wem trägst du das?",
      text: "Ein kleines Motiv am Handgelenk, das jemand anderes genauso trägt – da steckt eine Geschichte drin. Frag nach der Person dahinter, und du lernst gleich, was deinem Gegenüber wichtig ist.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe kennenlernen →",
    sceneLine: "Manche Verbindungen gehen unter die Haut. Bei Dich mit Stich beginnt vielleicht die nächste – mit Menschen, die Tattoos genauso lieben wie du.",
    pullQuote: "Sie erzählen unterschiedliche Geschichten und können außerdem Menschen miteinander verbinden.",
    related: ["partner-tattoos", "liebes-tattoo", "erste-tattoo-stechen-lassen"],
  },
  "geometric-sleeve-tattoo": {
    motif: "Geometric Sleeve",
    glanceTitle: "Geometric Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Linien", "Mandalas", "Dreiecke", "Symmetrie"] },
      { label: "Wirkt", items: ["Modern", "Präzise", "Zeitlos", "Minimalistisch"] },
      { label: "Oft kombiniert mit", items: ["Dotwork", "Mandala", "Negative Space"] },
    ],
    flirtHook: {
      title: "Präzision mit Persönlichkeit",
      text: "Wer sich für klare Linien und Symmetrie entscheidet, hat meist einen genauen Blick für Details. Frag, ob hinter dem Muster eine Idee steckt oder ob die Form selbst die Aussage ist.",
    },
    hookLinkLabel: "Geometric-Fans in deiner Nähe finden →",
    sceneLine: "Präzise Linien auf der Haut, klare Worte im Chat – so darf Kennenlernen sein. Bei Dich mit Stich ist dein Tattoo von Anfang an Teil des Profils.",
    pullQuote: "Der Stil lebt vor allem von klaren Formen, ruhigen Flächen und einem sauberen Gesamtbild.",
    related: ["mandala-tattoo", "tribal-maori-sleeve-tattoo", "trash-polka-sleeve-tattoo"],
  },
  "hawaiianische-tribal-tattoo": {
    motif: "Hawaiianisches Tribal",
    glanceTitle: "Hawaiianisches Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Herkunft", "Stärke", "Familie", "Naturverbundenheit"] },
      { label: "Typische Elemente", items: ["Tiefes Schwarz", "Klare Linien", "Wellen", "Körperverlauf"] },
      { label: "Vorher klären", items: ["Bedeutung der Symbole", "Passende Körperstelle", "Polynesian-Artist"] },
    ],
    flirtHook: {
      title: "Wellen im Gespräch",
      text: "Kräftige Schwarzflächen und fließende Linien fallen auf – ein natürlicher Anlass für eine Frage. Wie wichtig war die persönliche Bedeutung, wie wichtig die Wirkung? Daraus wird schnell ein Gespräch über mehr als Tinte.",
    },
    hookLinkLabel: "Tribal-Liebhaber in deiner Nähe finden →",
    sceneLine: "Markante Tattoos trägt, wer nicht unauffällig bleiben will. Bei Dich mit Stich triffst du Singles, die genau das an dir mögen.",
    pullQuote: "Sie erzählen Geschichten über Herkunft, Stärke, Familie und Naturverbundenheit – meist in tiefem Schwarz gestochen und mit klaren Linien.",
    related: ["polynesische-tribal-tattoo", "polynesian-tattoo", "tribal-tattoo"],
  },
  "indianer-tattoos": {
    motif: "Indianer & Tribal",
    glanceTitle: "Indianer Tattoos auf einen Blick",
    facts: [
      { label: "Typische Elemente", items: ["Linien", "Punkte", "Wirbel", "Abstrakte Formen"] },
      { label: "Steht für", items: ["Herkunft", "Gemeinschaft", "Rituale", "Zugehörigkeit"] },
      { label: "Vorher klären", items: ["Herkunft prüfen", "Persönlicher Bezug", "Offenes Studiogespräch"] },
    ],
    flirtHook: {
      title: "Neugier statt Klischee",
      text: "Hinter vielen Tribal-Motiven stehen Geschichte, Gemeinschaft und Rituale. Frag interessiert, welche Tradition dein Gegenüber inspiriert hat und wie es sich damit auseinandergesetzt hat. So wird aus Neugier schnell ein echtes Gespräch.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe finden →",
    sceneLine: "Du trägst ein Motiv mit Geschichte und wünschst dir jemanden, der danach fragt? Bei Dich mit Stich sind Tattoos Teil des Kennenlernens.",
    pullQuote: "Ein respektvoller Umgang beginnt damit, das Motiv nicht nur nach seiner Optik zu beurteilen, sondern auch nach seiner Herkunft und Bedeutung.",
    related: ["tribal-tattoo", "wolf-tattoo", "polynesian-tattoo"],
  },
  "japanische-tattoos": {
    motif: "Japanisch",
    glanceTitle: "Japanische Tattoos in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Drache", "Phönix", "Schlange", "Wächterlöwen", "Kirschblüten"] },
      { label: "Steht für", items: ["Stärke", "Weisheit", "Wiedergeburt", "Schutz", "Vergänglichkeit"] },
      { label: "Tradition", items: ["Irezumi", "Holzschnittkunst", "Frei gestochen"] },
    ],
    flirtHook: {
      title: "Drache trifft Phönix",
      text: "In der japanischen Tattookunst gelten Drache und Phönix oft als Gegenspieler. Frag, welches Motiv dein Gegenüber trägt und wofür es steht – Stärke, Neuanfang oder Wandel. Vielleicht ergänzt ihr euch ja besser als gedacht.",
    },
    hookLinkLabel: "Singles mit Tattoo in deiner Nähe kennenlernen →",
    sceneLine: "Ein Motiv mit jahrhundertealter Tradition verdient ein Gegenüber, das nachfragt. Bei Dich mit Stich ist das der ganz normale Einstieg.",
    pullQuote: "Dabei sind nicht nur die Motive, sondern auch das Handwerk fest in der japanischen Kultur verwurzelt.",
    related: ["sleeve-tattoo-japanese", "blumen-tattoos", "tattoo-stile"],
  },
  "kreuz-tattoos": {
    motif: "Kreuz",
    glanceTitle: "Kreuz Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Himmel & Erde", "Glaube", "Verbundenheit", "Leben & Tod"] },
      { label: "Bekannte Formen", items: ["Ägyptisches Anch", "Lateinisches Kreuz", "Malteserkreuz", "Baskisches Lauburu"] },
      { label: "Vorher klären", items: ["Bedeutung recherchieren", "Form genau prüfen", "Beratung im Studio"] },
    ],
    flirtHook: {
      title: "Glaube, Form, Geschichte",
      text: "Kreuz ist nicht gleich Kreuz – vom Anch bis zum Malteserkreuz steckt in jeder Form etwas anderes. Frag, warum es genau diese geworden ist. Oft landet ihr schnell bei den Dingen, die dem anderen wirklich wichtig sind.",
    },
    hookLinkLabel: "Singles mit Tattoos in deiner Nähe finden →",
    sceneLine: "Ein Kreuz auf der Haut ist selten Zufall. Bei Dich mit Stich lernst du Menschen kennen, die nach der Bedeutung fragen, bevor sie urteilen.",
    pullQuote: "Das Kreuz symbolisiert demzufolge die Verbundenheit zwischen dem Himmel und der Erde.",
    related: ["religious-sleeve-tattoo", "old-school-tattoos", "tattoo-motive"],
  },
  "liebes-tattoo": {
    motif: "Liebes-Tattoo",
    glanceTitle: "Liebes-Tattoo in 20 Sekunden",
    facts: [
      { label: "Beliebte Motive", items: ["Herzen", "Puzzleteile", "Sternzeichen", "Notenschlüssel", "Geteilte Sprüche"] },
      { label: "Vorher klären", items: ["Beide einverstanden", "Zeitloses Motiv", "Sichtbarkeit", "Körperstelle"] },
      { label: "Nicht nur für", items: ["Paare", "Eigene Kinder", "Den Lieblingsverein"] },
    ],
    flirtHook: {
      title: "Liebe, die bleibt",
      text: "Puzzleteile, Sternzeichen, zwei halbe Sprüche – Liebes-Tattoos sind heute kreativer als ein Name. Frag, welches Motiv dein Gegenüber für die große Liebe wählen würde, und ihr redet schnell über mehr als Tinte.",
    },
    hookLinkLabel: "Romantische Tätowierte in deiner Nähe entdecken →",
    sceneLine: "Bevor Liebe unter die Haut geht, muss sie erst einmal anfangen. Bei Dich mit Stich lernst du Singles kennen, die wissen, wie ernst ein Tattoo gemeint sein kann.",
    pullQuote: "Jeder Mensch, der sich ein Tattoo stechen lässt, hat das Bedürfnis, ein Gefühl, eine besondere Liebe oder einfach etwas auszudrücken, was ihn beschäftigt.",
    related: ["partner-tattoos", "liebes-tattoo-fehler-die-du-vermeiden-solltest", "freundschaftstattoo"],
  },
  "liebes-tattoo-fehler-die-du-vermeiden-solltest": {
    motif: "Liebes-Tattoo",
    glanceTitle: "Liebes-Tattoo: Fehler auf einen Blick",
    facts: [
      { label: "Lieber vermeiden", items: ["Porträt des Partners", "Voller Name", "Mainstream-Motive", "Tattoo als Überraschung"] },
      { label: "Bessere Ideen", items: ["Ergänzende Motive", "Puzzleteile", "Sternzeichen", "Gemeinsame Leidenschaften"] },
      { label: "Vorher prüfen", items: ["Zeitlos?", "Nicht zu privat?", "Gemeinsam entschieden?"] },
    ],
    flirtHook: {
      title: "Ex-Tattoo als Gesprächsstoff",
      text: "Fast jeder kennt jemanden mit einem Namen auf der Haut, der nicht mehr aktuell ist. Frag lieber, welches Motiv man sich heute für die Liebe stechen lassen würde – das verrät, wie jemand über Beziehungen denkt.",
    },
    hookLinkLabel: "Singles mit Herz und Tinte in deiner Nähe finden →",
    sceneLine: "Erst kennenlernen, dann gemeinsam stechen lassen – in dieser Reihenfolge. Bei Dich mit Stich machst du den ersten Schritt ganz ohne Nadel.",
    pullQuote: "Wichtig ist vor allem, dass das Tattoo auch dann noch passend wirkt, wenn die erste Euphorie nachlässt.",
    related: ["liebes-tattoo", "partner-tattoos", "tattoo-entfernen"],
  },
  "mandala-tattoo": {
    motif: "Mandala",
    glanceTitle: "Mandala Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Symmetrie", "Harmonie", "Spiritualität", "Innere Mitte"] },
      { label: "Typische Stile", items: ["Dotwork", "Blackwork", "Neo-Traditional"] },
      { label: "Beliebt auf", items: ["Rücken", "Wirbelsäule", "Schulter"] },
    ],
    flirtHook: {
      title: "Alles kreist ums Zentrum",
      text: "Ein Mandala baut sich aus seiner Mitte heraus auf. Frag, was für dein Gegenüber im Zentrum steht – Ruhe, Spiritualität oder einfach die Liebe zur perfekten Symmetrie. Die Antwort sagt viel darüber, wie jemand tickt.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Wer Symmetrie auf der Haut trägt, sucht oft auch im Leben Balance. Bei Dich mit Stich lernst du Menschen kennen, die dein Motiv zu schätzen wissen.",
    pullQuote: "Das Wort Mandala stammt aus dem Sanskrit und steht für Kreis, um den sich alles dreht.",
    related: ["geometric-sleeve-tattoo", "blumen-tattoos", "tattoo-stile"],
  },
  "maori-tattoo": {
    motif: "Maori",
    glanceTitle: "Maori Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Herkunft", "Identität", "Sozialer Rang", "Übergangsritus"] },
      { label: "Typische Muster", items: ["Taratarekae", "Unaunahi", "Hikuaaua", "Pakati"] },
      { label: "Beliebt auf", items: ["Arm", "Bein", "Rücken"] },
    ],
    flirtHook: {
      title: "Respekt als Gesprächsstart",
      text: "Hinter Maori-Mustern steckt eine lebendige Kultur, kein bloßes Ornament. Frag nach, wie dein Gegenüber zu seinem Motiv gekommen ist und was es ihm bedeutet – daraus entsteht oft ein Gespräch mit echtem Tiefgang.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe kennenlernen →",
    sceneLine: "Wer sich mit der Herkunft seines Motivs beschäftigt, sucht meist auch beim Kennenlernen mehr als Oberfläche. Bei Dich mit Stich bist du damit an der richtigen Adresse.",
    pullQuote: "Für Maori war das Tätowieren ein Übergangsritus, was bedeutete, dass es hoch verehrt und ritualisiert wurde.",
    related: ["maori-tribal-tattoo", "polynesian-tattoo", "tribal-maori-sleeve-tattoo"],
  },
  "maori-tribal-tattoo": {
    motif: "Maori Tribal",
    glanceTitle: "Maori Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Herkunft", "Identität", "Familie", "Mut"] },
      { label: "Typische Elemente", items: ["Markante Linien", "Fließende Formen", "Starke Symbolik"] },
      { label: "Darauf achten", items: ["Ta Moko respektieren", "Vorlagen nicht kopieren", "Stilsicherer Artist"] },
    ],
    flirtHook: {
      title: "Mehr als Ornament",
      text: "Maori-inspirierte Linien tragen oft eine bewusste Entscheidung in sich. Frag nicht nur, was das Motiv zeigt, sondern warum es dieser Stil geworden ist – die Antwort erzählt viel über Werte, Familie und Haltung.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe finden →",
    sceneLine: "Respekt vor der Symbolik, Geduld bei der Motivwahl – das verbindet. Auf Dich mit Stich lernst du Menschen kennen, die ihre Tattoos genauso ernst nehmen wie du.",
    pullQuote: "Ta Moko bezeichnet jedoch die traditionelle Tätowierkunst der Māori und ist eng mit Identität, Herkunft, Familiengeschichte und persönlichem Lebensweg verbunden.",
    related: ["maori-tattoo", "polynesische-tribal-tattoo", "tribal-maori-sleeve-tattoo"],
  },
  "mythology-sleeve-tattoo": {
    motif: "Mythology Sleeve",
    glanceTitle: "Mythology Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Figuren", items: ["Zeus", "Athena", "Odin", "Medusa"] },
      { label: "Stil", items: ["Black & Grey", "Realism", "Ornamentik"] },
      { label: "Darauf achten", items: ["Einheitlicher Stil", "Klares Hauptmotiv", "Ruhige Übergänge", "Lesbarkeit auf Distanz"] },
    ],
    flirtHook: {
      title: "Götter als Gesprächsstoff",
      text: "Zeus, Odin oder Medusa – hinter jeder Figur steckt eine Sage und meist auch eine persönliche Symbolik. Frag, welche Geschichte der Arm erzählt, und hör gut zu.",
    },
    hookLinkLabel: "Tätowierte Sagenfans in deiner Nähe finden →",
    sceneLine: "Ein Mythology Sleeve erzählt eine Geschichte über den ganzen Arm. Bei Dich mit Stich lernst du Singles kennen, die sie hören wollen – und ihre eigene mitbringen.",
    pullQuote: "Ein Mythology Sleeve wirkt meist dann am stimmigsten, wenn die Figuren nicht nur einzeln stark sind, sondern auch als Gesamtbild funktionieren.",
    related: ["das-wikinger-tattoo", "religious-sleeve-tattoo", "black-grey-sleeve-tattoo"],
  },
  "narben-taetowieren": {
    motif: "Narben-Cover-up",
    glanceTitle: "Narben tätowieren auf einen Blick",
    facts: [
      { label: "Vorher klären", items: ["Vollständige Heilung", "Hautärztliche Einschätzung", "Erfahrung mit Narben", "Realistische Erwartungen"] },
      { label: "Darauf achten", items: ["Tiefe der Narbe", "Größe", "Gewebestruktur", "Schmerzempfinden"] },
      { label: "Möglich", items: ["Ungleiche Farbhaltung", "Längere Heilung", "Nachstechen"] },
    ],
    flirtHook: {
      title: "Geschichten mit Tiefe",
      text: "Hinter manchem Motiv steckt mehr, als man auf den ersten Blick sieht. Wer eine Narbe in Kunst verwandelt hat, entscheidet selbst, wann und wie viel davon erzählt wird – ein offenes Ohr ohne Nachbohren ist der beste Anfang.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Jede Haut erzählt ihre eigene Geschichte. Bei Dich mit Stich begegnest du Menschen, die hinschauen, ohne zu urteilen.",
    pullQuote: "Das liegt vor allem daran, dass es sich bei Narbengewebe um keine natürliche Hautstruktur handelt.",
    related: ["cover-up-tattoos", "tattoo-studio", "wie-gefaehrlich-tattoo"],
  },
  "neo-traditional-sleeve-tattoo": {
    motif: "Neo-Traditional Sleeve",
    glanceTitle: "Neo-Traditional Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Tiger", "Eule", "Schiff", "Mythische Figuren"] },
      { label: "Stil", items: ["Kräftige Outlines", "Satte Farben", "Extrem kontrastreich"] },
      { label: "Mix aus", items: ["Tradition", "Moderne Illustration", "Storytelling"] },
    ],
    flirtHook: {
      title: "Old School, neu erzählt",
      text: "Tiger, Eule, Schiff – Neo-Traditional lebt von Motiven mit Symbolkraft. Frag, welches Bild die meiste Geschichte trägt. Bei so viel Farbe auf dem Arm ist der Gesprächseinstieg praktisch schon gemacht.",
    },
    hookLinkLabel: "Neo-Trad-Fans in deiner Nähe entdecken →",
    sceneLine: "Kräftige Linien, satte Farben, klare Haltung. Bei Dich mit Stich zeigst du deinen Sleeve dort, wo er als das gesehen wird, was er ist: ein Stück von dir.",
    pullQuote: "Beliebt sind Tiere, Schiffe oder mythische Figuren – modern interpretiert und extrem kontrastreich.",
    related: ["old-school-tattoos", "animal-sleeve-tattoo", "anker-tattoos"],
  },
  "old-school-tattoos": {
    motif: "Old School",
    glanceTitle: "Old School Tattoo in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Rose", "Schwalbe", "Anker", "Nautischer Stern", "Flammendes Herz"] },
      { label: "Erkennbar an", items: ["Schwarze Outlines", "Kräftige Farben", "Schlichte Formen"] },
      { label: "Herkunft", items: ["Seefahrt", "Matrosen", "Sailor Jerry"] },
    ],
    flirtHook: {
      title: "Seemannsgarn erwünscht",
      text: "Schwalbe, Anker, flammendes Herz – Old-School-Motive stehen oft für Liebe, Heimweh und Rückkehr. Frag, ob hinter dem Klassiker eine eigene Geschichte steckt oder einfach die Liebe zum Vintage-Look. Beides ist ein guter Anfang.",
    },
    hookLinkLabel: "Traditional-Fans in deiner Nähe entdecken →",
    sceneLine: "Klassiker mit klaren Linien und festen Werten – so darf auch das Kennenlernen sein. Bei Dich mit Stich findest du Singles, die dein Flash-Motiv sofort erkennen.",
    pullQuote: "Immer mehr Menschen erfreuten sich an diesem simplen Körperschmuck, der nicht selten von den Hoffnungen und Leiden der Seefahrer sprach.",
    related: ["anker-tattoos", "skull-tattoos", "neo-traditional-sleeve-tattoo"],
  },
  "partner-tattoos": {
    motif: "Partner-Tattoo",
    glanceTitle: "Partner-Tattoo in 20 Sekunden",
    facts: [
      { label: "Beliebte Motive", items: ["Verschlungene Herzen", "Tätowierte Ringe", "Schlüssel & Schloss", "Paar-Schriftzüge"] },
      { label: "Beliebt auf", items: ["Inneres Handgelenk", "Hinter dem Ohr", "Finger", "Nacken"] },
      { label: "Darauf achten", items: ["Auch einzeln stimmig", "Zeitlos", "Gut verdeckbar", "Keine intimen Details"] },
    ],
    flirtHook: {
      title: "Schlüssel sucht Schloss",
      text: "Wer ein halbes Motiv trägt, hat eine Geschichte zur anderen Hälfte – oder wartet noch auf sie. Frag, ob dein Gegenüber sich ein Partner-Tattoo vorstellen könnte, und du erfährst viel über Nähe und Verbindlichkeit.",
    },
    hookLinkLabel: "Deine andere Hälfte in deiner Nähe finden →",
    sceneLine: "Ein Partner-Tattoo braucht zuerst einen Partner. Bei Dich mit Stich suchst du unter Menschen, für die Tinte kein Hindernis, sondern Gemeinsamkeit ist.",
    pullQuote: "Partner-Tattoos können auch von guten Freunden oder Freundinnen oder Geschwistern als Zeichen der Verbundenheit angesehen werden.",
    related: ["liebes-tattoo", "freundschaftstattoo", "liebes-tattoo-fehler-die-du-vermeiden-solltest"],
  },
  "polynesian-tattoo": {
    motif: "Polynesian",
    glanceTitle: "Polynesian Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Identität", "Herkunft", "Rang", "Stärke & Mut"] },
      { label: "Typische Elemente", items: ["Haifischzähne", "Schildkröte", "Enata", "Tiki", "Stachelrochen"] },
      { label: "Herkunft", items: ["Polynesisches Dreieck", "Samoa", "Tahiti", "Marquesas"] },
    ],
    flirtHook: {
      title: "Jede Stelle spricht",
      text: "Bei polynesischen Tattoos zählt nicht nur das Motiv, sondern auch, wo es sitzt. Frag, warum die Schildkröte gerade auf dem Arm gelandet ist – daraus wird schnell ein Gespräch über Herkunft, Werte und das, was jemanden antreibt.",
    },
    hookLinkLabel: "Singles mit Tattoo in deiner Nähe kennenlernen →",
    sceneLine: "Dein Tattoo erzählt, woher du kommst und wofür du stehst. Bei Dich mit Stich triffst du Menschen, die solche Geschichten hören wollen.",
    pullQuote: "Da ihnen keine Schrift bekannt war, hielten sie ihre Geschichte mit Malereien und Schnitzereien fest und gaben sie so weiter.",
    related: ["polynesische-tribal-tattoo", "maori-tattoo", "tribal-tattoo"],
  },
  "polynesische-tribal-tattoo": {
    motif: "Polynesisches Tribal",
    glanceTitle: "Polynesisches Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Stärke", "Schutz", "Spiritualität", "Verbundenheit zu Ahnen"] },
      { label: "Typische Elemente", items: ["Klare Muster", "Fließende Linien", "Körperform betont"] },
      { label: "Vorher klären", items: ["Bedeutung der Symbole", "Passende Körperstelle", "Erfahrener Artist"] },
    ],
    flirtHook: {
      title: "Linien mit Herkunft",
      text: "Ein polynesisch inspiriertes Tribal entsteht selten aus einer Laune heraus. Frag, wie das Motiv entwickelt wurde und was es für sein Gegenüber bedeutet – so kommt ihr ganz nebenbei auf Reisen, Wurzeln und die eigene Geschichte.",
    },
    hookLinkLabel: "Tribal-Fans in deiner Nähe entdecken →",
    sceneLine: "Wer sich so viel Gedanken um Linien und Symbolik macht, will kein „Was heißt das denn?“ im Vorbeigehen. Bei Dich mit Stich triffst du Singles, die hinter einem Tribal mehr sehen als ein Muster.",
    pullQuote: "Jedes Motiv erzählt eine persönliche Geschichte und zeigt die tiefe Verbundenheit zu polynesischen Kulturen, Natur und den Ahnen Polynesiens.",
    related: ["polynesian-tattoo", "hawaiianische-tribal-tattoo", "maori-tribal-tattoo"],
  },
  "portrait-realism-sleeve-tattoo": {
    motif: "Portrait Realism Sleeve",
    glanceTitle: "Portrait Realism Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Fotorealistisches Gesicht", "Uhr", "Rose"] },
      { label: "Wirkt durch", items: ["Extreme Detailtreue", "Weiche Übergänge", "Emotion"] },
      { label: "Vorher klären", items: ["Erfahrener Realism-Artist", "Gute Referenzfotos", "Persönliche Bedeutung"] },
    ],
    flirtHook: {
      title: "Wer ist das da?",
      text: "Ein fotorealistisches Gesicht auf dem Arm macht neugierig – und ist oft ganz persönlich. Frag behutsam nach, was das Porträt bedeutet. Wer es erzählen mag, zeigt dir damit ein echtes Stück von sich.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe finden →",
    sceneLine: "Ein Porträt unter der Haut trägt man nicht nebenbei. Bei Dich mit Stich lernst du Singles kennen, die solche Geschichten mit Respekt behandeln.",
    pullQuote: "Eine Uhr oder eine Rose ergänzt ein Porträt nicht nur optisch, sondern kann dem Motiv mehr Tiefe und Charakter geben.",
    related: ["black-grey-sleeve-tattoo", "floral-sleeve-tattoo", "tattoo-studio"],
  },
  "religious-sleeve-tattoo": {
    motif: "Religious Sleeve",
    glanceTitle: "Religious Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Jesus", "Maria", "Engel", "Rosenkranz"] },
      { label: "Stil", items: ["Black & Grey", "Feine Schattierungen", "Ruhige Gesamtwirkung"] },
      { label: "Oft kombiniert mit", items: ["Wolken", "Hände", "Lichtstimmungen", "Florale Details"] },
    ],
    flirtHook: {
      title: "Glaube, Bild, Geschichte",
      text: "Ein Religious Sleeve hat für die meisten Träger eine persönliche Bedeutung. Frag mit echtem Interesse und ohne Wertung, welche Symbole für sie oder ihn am wichtigsten sind – solche Gespräche gehen oft tiefer als erwartet.",
    },
    hookLinkLabel: "Singles mit Sinn für Symbolik in deiner Nähe finden →",
    sceneLine: "Manche Tattoos erzählt man nicht jedem. Bei Dich mit Stich findest du Menschen, die verstehen, dass hinter einem Motiv oft mehr steckt als Optik.",
    pullQuote: "Gesichter, Hände, Wolken, Lichtstimmungen oder florale Details können einen Religious Sleeve ruhig, würdevoll und sehr ausdrucksstark erscheinen lassen.",
    related: ["kreuz-tattoos", "mythology-sleeve-tattoo", "black-grey-sleeve-tattoo"],
  },
  "skull-fire-sleeve-tattoo": {
    motif: "Skull & Fire Sleeve",
    glanceTitle: "Skull & Fire Sleeve in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Vergänglichkeit", "Energie", "Rebellion"] },
      { label: "Umsetzung", items: ["Farbige Flammen", "Düster in B&G", "Realistischer Schädel"] },
      { label: "Aufbau über", items: ["Oberarm", "Ellenbogen", "Unterarm"] },
    ],
    flirtHook: {
      title: "Feuer statt Floskeln",
      text: "Schädel und Flammen wirken dramatisch – die Geschichte dahinter ist oft überraschend persönlich. Frag, ob es eher um Vergänglichkeit, Energie oder ein Stück Rebellion geht.",
    },
    hookLinkLabel: "Singles mit Feuer in deiner Nähe entdecken →",
    sceneLine: "Wer Totenkopf und Flammen trägt, kennt die schrägen Blicke. Bei Dich mit Stich zählt dein Sleeve als Statement – und nicht als Warnsignal.",
    pullQuote: "Skull & Fire Sleeves kombinieren Totenköpfe mit lodernden Flammen – ein kraftvolles Motiv zwischen Vergänglichkeit, Energie und Rebellion.",
    related: ["skull-tattoos", "biomechanical-sleeve-tattoo", "black-grey-sleeve-tattoo"],
  },
  "skull-tattoos": {
    motif: "Skull",
    glanceTitle: "Skull Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Vergänglichkeit", "Memento Mori", "Erinnerung", "Glücksbringer", "Leben & Tod als Einheit"] },
      { label: "Beliebt auf", items: ["Hand", "Oberarm", "Unterarm", "Brust"] },
      { label: "Oft kombiniert mit", items: ["Rosen", "Schlangen", "Schriftzüge", "Sugar-Skull-Ornamente"] },
    ],
    flirtHook: {
      title: "Eisbrecher mit Tiefgang",
      text: "Ein Totenkopf ist selten nur Deko. Frag nach der Geschichte dahinter – Memento Mori, Erinnerung an jemanden oder pure Liebe zum Old School? Die Antwort verrät mehr als jedes Profilbild.",
    },
    hookLinkLabel: "Skull-Fans in deiner Nähe entdecken →",
    sceneLine: "Wer einen Schädel trägt, hat genug von „Ist das nicht ein bisschen düster?“. Bei Dich mit Stich zeigen Singles ihre Tattoos im Profil – hier versteht man dein Motiv.",
    pullQuote: "Im 21. Jahrhundert ist er längst in der Popkultur angekommen und wird oft nur unter ästhetischen Aspekten betrachtet.",
    related: ["old-school-tattoos", "blumen-tattoos", "wolf-tattoo"],
  },
  "sleeve-tattoo": {
    motif: "Sleeve",
    glanceTitle: "Sleeve Tattoo auf einen Blick",
    facts: [
      { label: "Varianten", items: ["Viertel-Sleeve", "Half-Sleeve", "3/4-Sleeve", "Full-Sleeve"] },
      { label: "Gestochen auf", items: ["Arm", "Bein"] },
      { label: "Vorher klären", items: ["Motividee", "Stil", "Mehrere Sitzungen", "Gesamtgeschichte"] },
    ],
    flirtHook: {
      title: "Ein Arm voller Kapitel",
      text: "In einem Sleeve stecken meist eigene Geschichten – Lebensereignisse, Werte, Interessen. Frag, welches Motiv zuerst kam und welches zuletzt. So erzählt dir dein Gegenüber ganz nebenbei ein Stück seines Lebens.",
    },
    hookLinkLabel: "Sleeve-Träger in deiner Nähe entdecken →",
    sceneLine: "Ein ganzer Arm voller Geschichten verdient jemanden, der zuhört. Bei Dich mit Stich zeigen Singles ihre Tattoos – und fragen gern nach.",
    pullQuote: "In einem Sleeve Tattoo werden meistens eigene Geschichten erzählt.",
    related: ["neo-traditional-sleeve-tattoo", "japanische-tattoos", "black-grey-sleeve-tattoo"],
  },
  "sleeve-tattoo-japanese": {
    motif: "Japanese Sleeve",
    glanceTitle: "Japanese Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Motive", items: ["Drache", "Koi-Fisch", "Kirschblüten", "Samurai", "Wellen"] },
      { label: "Steht für", items: ["Stärke & Schutz", "Durchhaltevermögen", "Vergänglichkeit", "Ehre & Loyalität"] },
      { label: "Vorher klären", items: ["Armabdeckung", "Passende Motive", "Spezialisierter Tätowierer"] },
    ],
    flirtHook: {
      title: "Drache oder Koi?",
      text: "Im Japanese Sleeve hat jedes Motiv seine Bedeutung – der Koi steht für Durchhaltevermögen, der Drache für Stärke und Schutz. Frag, welches Symbol deinem Gegenüber am meisten bedeutet. Das erzählt oft eine ganze Geschichte.",
    },
    hookLinkLabel: "Japanese-Style-Fans in deiner Nähe finden →",
    sceneLine: "Ein Japanese Sleeve braucht Zeit, Geduld und eine klare Idee – genau wie gutes Kennenlernen. Bei Dich mit Stich fängt beides mit einem Blick auf dein Tattoo an.",
    pullQuote: "Besonders spannend ist dabei die Kombination aus klarer Bildsprache, fließender Komposition und persönlicher Bedeutung.",
    related: ["japanische-tattoos", "sleeve-tattoo", "black-grey-sleeve-tattoo"],
  },
  "space-galaxy-sleeve-tattoo": {
    motif: "Space & Galaxy Sleeve",
    glanceTitle: "Space & Galaxy Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Astronaut", "Planeten", "Nebel", "Galaxien", "Sterne"] },
      { label: "Wirkt durch", items: ["Leuchtende Farben", "Tiefe Kontraste", "Surreale Dynamik", "Starke Fernwirkung"] },
      { label: "Vorher klären", items: ["Dunkel oder farbig", "Realistisch oder abstrakt", "Zentrales Hauptmotiv"] },
    ],
    flirtHook: {
      title: "Kurs auf Gesprächsstoff",
      text: "Wer das Universum auf dem Arm trägt, hat meist auch eine Lieblingsfrage ans Universum. Frag, warum es gerade Astronaut, Planeten oder Nebel geworden sind – daraus wird schnell mehr als Small Talk.",
    },
    hookLinkLabel: "Tätowierte Sternengucker in deiner Nähe entdecken →",
    sceneLine: "Ein Arm voller Galaxien fällt auf – und verdient ein Gegenüber, das ihn wirklich anschaut. Bei Dich mit Stich treffen sich Singles, für die Tattoos Teil der Geschichte sind.",
    pullQuote: "Der Stil lebt von Tiefe, Kontrasten und einer Bildsprache, die oft zwischen realistischen Elementen und träumerischen Farbverläufen steht.",
    related: ["watercolor-sleeve-tattoo", "neo-traditional-sleeve-tattoo", "sleeve-tattoo"],
  },
  "tattoo-entfernen": {
    motif: "Tattoo entfernen",
    glanceTitle: "Tattoo entfernen: das Wichtigste",
    facts: [
      { label: "Methoden", items: ["Lasertherapie", "Übertätowieren", "Dermabrasion", "Chemisches Peeling", "Operative Entfernung"] },
      { label: "Dauer hängt ab von", items: ["Größe", "Alter", "Farbe", "Stechqualität"] },
      { label: "Vorher klären", items: ["Kosten", "Anzahl Sitzungen", "Narbenrisiko", "Wer behandelt"] },
    ],
    flirtHook: {
      title: "Neuanfang auf der Haut",
      text: "Ein Tattoo, das nicht mehr passt, erzählt oft von einem Kapitel, das vorbei ist. Wer offen darüber spricht, zeigt Humor und Selbstreflexion – und genau das macht ein Gespräch unter Tätowierten spannend.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe finden →",
    sceneLine: "Ob gelasert, überstochen oder mit Stolz behalten – jedes Tattoo hat seine Geschichte. Bei Dich mit Stich triffst du Menschen, die das verstehen.",
    pullQuote: "Doch was ist, wenn das Motiv nicht mehr gefällt oder die Liebelei, die die Tätowierung der Welt zeigen sollte, endet?",
    related: ["cover-up-tattoos", "liebes-tattoo-fehler-die-du-vermeiden-solltest", "tattoos-im-alter"],
  },
  "tattoo-flirt": {
    motif: "Tattoo-Flirt",
    glanceTitle: "Flirten über Tattoos: das Wichtigste",
    facts: [
      { label: "So klappt der Einstieg", items: ["Ehrliche Neugier", "Frage zum Motiv", "Kurzes Kompliment"] },
      { label: "Lieber lassen", items: ["Starren", "Plumpe Sprüche", "Motiv vorschnell deuten"] },
      { label: "Beliebte Stellen", items: ["Fuß & Knöchel", "Schultern", "Rücken", "Oberarme"] },
    ],
    flirtHook: {
      title: "Der Opener ist schon da",
      text: "Du musst dir keinen perfekten Spruch zurechtlegen – ein ehrliches „Was bedeutet dein Motiv?“ reicht oft. Und wenn das Gegenüber lieber über etwas anderes spricht, wechselst du einfach entspannt das Thema.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe ansprechen →",
    sceneLine: "Wo alle Tattoos tragen, ist die erste Frage schon gestellt. Bei Dich mit Stich kommst du über dein Motiv ganz unverkrampft ins Gespräch.",
    pullQuote: "Tattoos können ein einfacher Gesprächsanlass sein, aber sie ersetzen keinen natürlichen Einstieg.",
    related: ["frauen-tattoos", "tattoo-motive", "partner-tattoos"],
  },
  "tattoo-motive": {
    motif: "Tattoo-Motive",
    glanceTitle: "Beliebte Tattoo-Motive auf einen Blick",
    facts: [
      { label: "Klassiker", items: ["Anker", "Schwalbe", "Skull", "Wolf", "Tribal"] },
      { label: "Verspielt & im Trend", items: ["Einhorn", "Schmetterling", "Kirschen", "Pin-up"] },
      { label: "Vorher klären", items: ["Passt zur Körperstelle?", "Geplante Größe", "Gefällt es dauerhaft?"] },
    ],
    flirtHook: {
      title: "Anker oder Einhorn?",
      text: "Welches Motiv jemand wählt, sagt oft mehr als ein langer Profiltext. Frag nach dem Klassiker oder dem Trendmotiv – und ob es heute noch genauso gefällt wie am Tag des Stechens. Da wird es meist ehrlich und oft auch lustig.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Ob Schwalbe, Mandala oder Totenkopf – bei Dich mit Stich ist dein Motiv kein Makel, sondern ein Gesprächsanfang.",
    pullQuote: "Ein gutes Tattoo Motiv ist nicht nur hübsch, sondern sollte auch langfristig gefallen.",
    related: ["tattoo-stile", "anker-tattoos", "erste-tattoo-stechen-lassen"],
  },
  "tattoo-schriftzuege-schriftarten": {
    motif: "Schriftzug",
    glanceTitle: "Tattoo-Schriftzug in 20 Sekunden",
    facts: [
      { label: "Beliebte Inhalte", items: ["Namen der Liebsten", "Wichtige Daten", "Lieblingsverse", "Lateinische Sprüche"] },
      { label: "Schriftstile", items: ["Handgeschriebene Skripte", "Filigrane Buchstaben", "Gothic", "Vintage"] },
      { label: "Darauf achten", items: ["Lesbarkeit", "Schriftgröße", "Platzierung", "Stil zum Inhalt"] },
    ],
    flirtHook: {
      title: "Worte unter der Haut",
      text: "Ein Schriftzug ist eine Einladung zum Nachfragen: Wessen Name, welcher Vers, warum genau diese Zeile? Wer die Geschichte hinter den Buchstaben kennt, kennt ein Stück vom Menschen.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Manche Sätze trägt man ein Leben lang. Bei Dich mit Stich lernst du Singles kennen, die ihre Worte mit Bedacht gewählt haben – auf der Haut wie im Chat.",
    pullQuote: "Ein Tattoo sollte nicht mal eben aus einer Laune heraus, ohne Bedeutung gestochen werden, der Körperschmuck will wohlüberlegt sein.",
    related: ["liebes-tattoo", "tattoo-motive", "tattoo-stile"],
  },
  "tattoo-stile": {
    motif: "Tattoo-Stile",
    glanceTitle: "Tattoo-Stile in 20 Sekunden",
    facts: [
      { label: "Klassiker", items: ["Old School", "New School", "Oriental"] },
      { label: "Modern & grafisch", items: ["Trash Polka", "Dotwork", "Geometrisch", "Aquarell"] },
      { label: "Schwarz & reduziert", items: ["New Black", "Black and Grey", "Lineart", "Carvings"] },
    ],
    flirtHook: {
      title: "Welcher Stil bist du?",
      text: "Old School oder Dotwork, Trash Polka oder Black and Grey – der Lieblingsstil sagt viel über den Geschmack. Frag nach, warum jemand genau diesen Stil trägt, und ihr seid mitten im Gespräch.",
    },
    hookLinkLabel: "Singles mit deinem Tattoo-Stil in deiner Nähe finden →",
    sceneLine: "Ob klare Outlines oder Wasserfarbenkleckse: Bei Dich mit Stich zählt, was unter die Haut geht – und wer deinen Stil zu schätzen weiß.",
    pullQuote: "Denn die Wahl von einem modernen Motiv in „alter“ Umsetzung verleiht dem Motiv oftmals einen zusätzlichen Pepp.",
    related: ["old-school-tattoos", "trash-polka-sleeve-tattoo", "tattoo-motive"],
  },
  "tattoo-studio": {
    motif: "Tattoo-Studio",
    glanceTitle: "Gutes Tattoo-Studio: das Wichtigste",
    facts: [
      { label: "Darauf achten", items: ["Portfolio", "Sauberkeit", "Offene Beratung", "Passender Stil", "Vertrauen"] },
      { label: "Hygiene-Check", items: ["Getrennter Arbeitsbereich", "Desinfektion", "Einweghandschuhe", "Sterile Nadeln"] },
      { label: "Typische Fehler", items: ["Nur auf Preis", "Portfolio überspringen", "Fragen verschweigen"] },
    ],
    flirtHook: {
      title: "Wer sticht bei dir?",
      text: "Fast jeder Tätowierte hat ein Lieblingsstudio oder einen Artist, auf den er schwört. Frag nach Empfehlungen – das ist ein unkomplizierter Einstieg und verrät viel über Geschmack und Anspruch.",
    },
    hookLinkLabel: "Tattoo-Fans in deiner Nähe finden →",
    sceneLine: "Das richtige Studio findest du über Vertrauen und Empfehlungen – die richtigen Menschen auch. Schau dich bei Dich mit Stich um, wer in deiner Nähe Tinte trägt.",
    pullQuote: "Wenn du ein gutes Tattoo-Studio für dich finden willst, ist die alles entscheidende Frage, wie der Tätowierer ist.",
    related: ["erste-tattoo-stechen-lassen", "wie-gefaehrlich-tattoo", "tattoo-stile"],
  },
  "tattoos-fuer-maenner": {
    motif: "Tattoos für Männer",
    glanceTitle: "Tattoos für Männer auf einen Blick",
    facts: [
      { label: "Klassische Stile", items: ["Sailor Tattoos", "Japanisch", "Native American", "Maori"] },
      { label: "Moderne Ideen", items: ["Trash Polka", "Kid Art", "Kleine Symbole"] },
      { label: "Beliebte Stellen", items: ["Oberarm", "Rücken", "Schulter", "Brust", "Handgelenk"] },
    ],
    flirtHook: {
      title: "Mehr als nur Tinte",
      text: "Ein Sailor-Motiv erzählt von Abenteuern, Kid Art von der Liebe zu den eigenen Kindern. Frag nach der Geschichte hinter seinem Tattoo – da steckt oft mehr Gefühl drin, als man denkt.",
    },
    hookLinkLabel: "Tätowierte Männer in deiner Nähe entdecken →",
    sceneLine: "Ein Tattoo trägt man voller Stolz – am liebsten vor Menschen, die es zu schätzen wissen. Bei Dich mit Stich bist du unter Gleichgesinnten.",
    pullQuote: "Ein Tattoo ist Ausdruck der eigenen Persönlichkeit, der eigenen Werte und der eigenen Geschichte.",
    related: ["frauen-tattoos", "tattoo-stile", "japanische-tattoos"],
  },
  "tattoos-geeignet-fuer-jedes-alter": {
    motif: "Tattoos in jedem Alter",
    glanceTitle: "Tattoos in jedem Alter: das Wichtigste",
    facts: [
      { label: "Kernaussage", items: ["Kein Alterslimit", "Wohlbefinden zählt", "Ausdruck der Persönlichkeit"] },
      { label: "Stellen, die gut altern", items: ["Rücken", "Schulter", "Schlüsselbein", "Unterarm-Innenseite"] },
      { label: "Darauf achten", items: ["Regelmäßig nachstechen", "Professionelles Studio", "Sorgfältige Nachsorge"] },
    ],
    flirtHook: {
      title: "Tinte kennt kein Alter",
      text: "Ob mit 25 oder mit 55: Wer tätowiert ist, möchte nicht erst erklären müssen, warum. Frag lieber nach der Geschichte hinter dem ersten Motiv – und wann das letzte dazukam.",
    },
    hookLinkLabel: "Gleichgesinnte in deiner Nähe finden →",
    sceneLine: "Ablehnung wegen deiner Tattoos? Nicht hier. Bei Dich mit Stich treffen sich tätowierte Singles jeden Alters, die dein Motiv eher neugierig macht als abschreckt.",
    pullQuote: "Mittlerweile gilt der Körperschmuck als Ausdruck der eigenen Persönlichkeit, als Zierde und untermalt eher jeden Einzelnen.",
    related: ["tattoos-im-alter", "erste-tattoo-stechen-lassen", "tattoo-flirt"],
  },
  "tattoos-im-alter": {
    motif: "Tattoos im Alter",
    glanceTitle: "Tattoos im Alter: das Wichtigste",
    facts: [
      { label: "Vorher fragen", items: ["Passt es später?", "Eigenes Motiv", "Kein Partnername", "Kein Gruppenzwang"] },
      { label: "Mit der Zeit", items: ["Haut verliert Straffheit", "Farben bleichen eher", "Schwarz hält länger"] },
      { label: "Hilft langfristig", items: ["Klares Motiv", "Überlegte Stelle", "Gute Pflege", "Nachstechen"] },
    ],
    flirtHook: {
      title: "Tinte mit Lebenserfahrung",
      text: "Ein Tattoo, das nach Jahren noch passt, zeigt, dass jemand weiß, was er will. Frag, welches Motiv am längsten dabei ist und ob es heute noch dieselbe Bedeutung hat – da kommen oft die schönsten Geschichten.",
    },
    hookLinkLabel: "Tätowierte Singles jeden Alters in deiner Nähe finden →",
    sceneLine: "Tattoos kennen kein Verfallsdatum – Anziehung auch nicht. Bei Dich mit Stich triffst du Singles, die zu ihrer Tinte stehen – in jeder Lebensphase.",
    pullQuote: "Wer wirklich glücklich verliebt ist, muss es niemandem beweisen.",
    related: ["tattoos-geeignet-fuer-jedes-alter", "liebes-tattoo-fehler-die-du-vermeiden-solltest", "tattoo-entfernen"],
  },
  "trash-polka-sleeve-tattoo": {
    motif: "Trash Polka Sleeve",
    glanceTitle: "Trash Polka Sleeve in 20 Sekunden",
    facts: [
      { label: "Farben", items: ["Schwarz", "Rote Akzente"] },
      { label: "Typische Elemente", items: ["Realistisches Porträt", "Geometrie", "Splatter", "Pinselstriche", "Typografie"] },
      { label: "Wirkt", items: ["Expressiv", "Grafisch", "Urban", "Bewusst auffällig"] },
    ],
    flirtHook: {
      title: "Schwarz, Rot, direkt",
      text: "Trash Polka ist nichts für Zurückhaltende – und das gilt oft auch für die Menschen, die ihn tragen. Frag, welches Element auf dem Arm zuerst da war: das Porträt, die Schrift oder das Rot.",
    },
    hookLinkLabel: "Trash-Polka-Fans in deiner Nähe entdecken →",
    sceneLine: "Wer einen Arm in Schwarz und Rot trägt, will nicht übersehen werden. Bei Dich mit Stich ist dein Sleeve kein Hingucker am Rande, sondern ein Gesprächsanfang.",
    pullQuote: "Gerade als Sleeve wirkt dieser Stil besonders intensiv, weil er über den ganzen Arm hinweg mit Kontrasten, Bewegung und klaren Blickfängen arbeitet.",
    related: ["tattoo-stile", "geometric-sleeve-tattoo", "portrait-realism-sleeve-tattoo"],
  },
  "tribal-maori-sleeve-tattoo": {
    motif: "Tribal / Maori Sleeve",
    glanceTitle: "Tribal / Maori Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Formen", items: ["Spiralen", "Dreiecke", "Koru-Formen"] },
      { label: "Wirkt", items: ["Grafisch", "Zeitlos", "Symbolstark", "Sattes Schwarz"] },
      { label: "Darauf achten", items: ["Kulturelle Bedeutungen", "Exakte Linienführung", "Passende Platzierung"] },
    ],
    flirtHook: {
      title: "Linien mit Herkunft",
      text: "Tribal- und Maori-Muster tragen kulturelle Symbolik, das Koru etwa steht für Neubeginn. Frag respektvoll, was deinem Gegenüber an diesen Formen wichtig ist – und woher die Verbindung dazu kommt.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe entdecken →",
    sceneLine: "Klare Linien, sattes Schwarz, starke Symbolik: Dein Sleeve spricht für sich. Bei Dich mit Stich triffst du Menschen, die Tattoos nicht nur ansehen, sondern verstehen wollen.",
    pullQuote: "Der Stil passt besonders gut, wenn du eine klare, markante Optik suchst und Wert auf starke Kontraste legst.",
    related: ["maori-tattoo", "maori-tribal-tattoo", "polynesian-tattoo"],
  },
  "tribal-tattoo": {
    motif: "Tribal",
    glanceTitle: "Tribal Tattoo in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Schwarze Ornamente", "Geschwungene Linien", "Punkte & Kreise", "Dreiecke"] },
      { label: "Herkunft", items: ["Indonesien", "Tahiti", "Neuseeland"] },
      { label: "Darauf achten", items: ["Wirkung", "Körperstelle", "Kultureller Hintergrund"] },
    ],
    flirtHook: {
      title: "Comeback mit Geschichte",
      text: "Tribals haben einen weiten Weg hinter sich – von alten Stammeszeichen bis zum 90er-Comeback. Frag, ob dein Gegenüber seins wegen der Optik oder der Herkunft gewählt hat. Beide Antworten erzählen viel über den Menschen dahinter.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Nähe finden →",
    sceneLine: "Klare Linien, starke Formen – und kein Bock mehr auf dumme Sprüche? Bei Dich mit Stich treffen sich Singles, für die Tattoos einfach dazugehören.",
    pullQuote: "Ein Tribal ist bedeutungsvoller, je mehr Gebilde und somit auch Bedeutungen darin enthalten sind.",
    related: ["maori-tribal-tattoo", "polynesische-tribal-tattoo", "indianer-tattoos"],
  },
  "vegane-tattoos": {
    motif: "Veganes Tattoo",
    glanceTitle: "Veganes Tattoo auf einen Blick",
    facts: [
      { label: "Nachfragen bei", items: ["Tattoofarbe", "Rasierer", "Matrizenpapier", "Tattooseife", "Heilsalbe"] },
      { label: "Oft nicht vegan", items: ["Knochenkohle", "Wollwachs", "Gelatine", "Tierisches Glycerin"] },
      { label: "Vorher klären", items: ["Farbmarke", "Studio-Einrichtung", "Werte des Artists", "Veganes Studio?"] },
    ],
    flirtHook: {
      title: "Werte, die verbinden",
      text: "Wer beim Tattoo sogar nach Matrizenpapier und Heilsalbe fragt, lebt seine Überzeugung konsequent. Frag, wie das Studio auf vegane Wünsche reagiert hat – so merkt ihr schnell, ob ihr ähnlich tickt.",
    },
    hookLinkLabel: "Vegan lebende Tätowierte in deiner Nähe entdecken →",
    sceneLine: "Tinte ohne Tierleid, Haltung mit Stil: Bei Dich mit Stich findest du Singles, die bei ihrem Körperschmuck genauso genau hinschauen wie du.",
    pullQuote: "Nicht nur die Farbe, sondern auch die Kunst geht unter die Haut und da kann es wichtig sein, mit dem Künstler bestimmte Werte zu teilen.",
    related: ["tattoo-studio", "erste-tattoo-stechen-lassen", "wie-gefaehrlich-tattoo"],
  },
  "vogel-tattoos": {
    motif: "Vogel",
    glanceTitle: "Vogel Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Freiheit", "Wiedergeburt", "Stärke", "Weisheit", "Verwandlung"] },
      { label: "Beliebte Vögel", items: ["Phönix", "Schwalbe", "Kolibri", "Adler", "Eule"] },
      { label: "Oft kombiniert mit", items: ["Blumen", "Herzen", "Kreuz"] },
    ],
    flirtHook: {
      title: "Phönix oder Schwalbe?",
      text: "Vom Phönix für den Neuanfang bis zur Schwalbe für die Freiheit – jeder Vogel erzählt etwas anderes. Frag, welcher es geworden ist und warum. Manchmal steckt eine ganze Verwandlung dahinter, manchmal einfach Liebe zum Motiv.",
    },
    hookLinkLabel: "Freigeister mit Tattoo in deiner Nähe entdecken →",
    sceneLine: "Freiheit auf der Haut, aber trotzdem Lust auf jemanden an deiner Seite? Bei Dich mit Stich sind Tattoos kein Randthema, sondern ein guter Anfang.",
    pullQuote: "Viele von uns Menschen möchten auch gerne so grenzenlos frei sein und entscheiden sich unter anderem deshalb für ein Vogel Tattoo.",
    related: ["blumen-tattoos", "old-school-tattoos", "wolf-tattoo"],
  },
  "watercolor-sleeve-tattoo": {
    motif: "Watercolor Sleeve",
    glanceTitle: "Watercolor Sleeve in 20 Sekunden",
    facts: [
      { label: "Typische Elemente", items: ["Farbspritzer", "Pinselstriche", "Transparenzen", "Lotusblüte"] },
      { label: "Oft kombiniert mit", items: ["Florale Motive", "Tiere", "Schriftzüge", "Geometrie"] },
      { label: "Vorher klären", items: ["Farbstimmung", "Watercolor-Portfolio", "Mehrere Sitzungen"] },
    ],
    flirtHook: {
      title: "Farbe ins Gespräch",
      text: "Ein Watercolor Sleeve sieht aus wie ein Gemälde auf der Haut. Frag nach der Farbstimmung – warum gerade diese Töne? Oft steckt dahinter mehr Gefühl, als man auf den ersten Blick sieht.",
    },
    hookLinkLabel: "Kreative Tätowierte in deiner Nähe entdecken →",
    sceneLine: "Fließende Farben statt harter Linien – und ein Kennenlernen ohne steife Floskeln. Bei Dich mit Stich darf dein Arm zeigen, wie bunt du bist.",
    pullQuote: "Der Stil wirkt oft leicht, lebendig und dynamisch, weil Farben nicht streng abgegrenzt sind, sondern ineinanderlaufen können.",
    related: ["floral-sleeve-tattoo", "space-galaxy-sleeve-tattoo", "blumen-tattoos"],
  },
  "wie-gefaehrlich-tattoo": {
    motif: "Tattoo-Risiken",
    glanceTitle: "Tattoo-Risiken: das Wichtigste",
    facts: [
      { label: "Mögliche Risiken", items: ["Entzündungen", "Narbenbildung", "Allergien"] },
      { label: "Studio prüfen", items: ["Hygienestandards", "Sterile Nadeln", "Geprüfte Farben", "Sorgfältige Aufklärung"] },
      { label: "Nach dem Stechen", items: ["Dünn eincremen", "Kruste nicht entfernen", "Nur lauwarm duschen"] },
    ],
    flirtHook: {
      title: "Gut beraten, gut gestochen",
      text: "Wie hast du dein Studio gefunden? Die Frage klingt nüchtern, bringt aber oft die besten Geschichten hervor – vom akribischen Vorgespräch bis zur Pflege-Routine danach. Und du erfährst nebenbei, wie sorgfältig jemand Entscheidungen trifft.",
    },
    hookLinkLabel: "Tätowierte Singles in deiner Stadt finden →",
    sceneLine: "Tipps zum richtigen Studio tauscht man am besten mit Leuten aus, die selbst schon unter der Nadel lagen. Bei Dich mit Stich sind das alle.",
    pullQuote: "Wie groß das Risiko im Einzelfall ist, hängt unter anderem von der Haut, der Hygiene und den verwendeten Farben ab.",
    related: ["tattoo-studio", "erste-tattoo-stechen-lassen", "vegane-tattoos"],
  },
  "wolf-tattoo": {
    motif: "Wolf",
    glanceTitle: "Wolf Tattoo in 20 Sekunden",
    facts: [
      { label: "Steht für", items: ["Stärke", "Loyalität", "Familie", "Ausdauer"] },
      { label: "Oft kombiniert mit", items: ["Mond", "Federn", "Adler", "Berge", "Tribal"] },
      { label: "Beliebt auf", items: ["Rücken", "Oberarm", "Schulterblatt"] },
    ],
    flirtHook: {
      title: "Einsamer Wolf? Muss nicht",
      text: "Der Wolf steht für Rudel, Familie und Loyalität – und dafür, dass er seinen Partner nicht wechselt. Frag, ob dein Gegenüber eher Einzelgänger oder Rudeltier ist. Die Antwort verrät einiges darüber, was jemand sucht.",
    },
    hookLinkLabel: "Dein Rudel in deiner Nähe finden →",
    sceneLine: "Heulender Wolf auf dem Rücken, aber keine Lust mehr auf Alleingang? Bei Dich mit Stich triffst du Singles, die Tattoos genauso ernst nehmen wie du.",
    pullQuote: "Zudem wechselt der Wolf nicht seinen Partner und das Rudel kümmert sich um die Nachkommen.",
    related: ["animal-sleeve-tattoo", "das-wikinger-tattoo", "tattoos-fuer-maenner"],
  },
};
